package main

import (
	"fmt"
	"math"
	"sort"
	"strings"

	"github.com/fall-out-bug/sdp_lab/internal/inference/decompose"
	"github.com/fall-out-bug/sdp_lab/internal/inference/decompose/adapters/wsverdict"
	"github.com/fall-out-bug/sdp_lab/internal/inference/replayutil"
)

// reportData aggregates all bench results for markdown rendering.
type reportData struct {
	RunID    string
	Corpus   string
	DryRun   bool
	Records  []replayutil.RunRecord
	Results  []benchResult
	Fixtures []replayutil.Fixture
}

// renderReport generates the A/B comparison markdown report.
func renderReport(d reportData) string {
	var b strings.Builder

	b.WriteString("# F146 Decomposition A/B Benchmark Report\n\n")
	b.WriteString(fmt.Sprintf("**Run ID:** %s  \n", d.RunID))
	b.WriteString(fmt.Sprintf("**Corpus:** %s  \n", d.Corpus))
	b.WriteString(fmt.Sprintf("**Fixtures:** %d  \n", len(d.Results)))
	if d.DryRun {
		b.WriteString("\n> ⚠️ **DRY-RUN MODE** — responses generated by deterministic mock LLM, not a real model.\n> Token counts and costs are estimates. Re-run with `OPENROUTER_API_KEY` set for real numbers.\n")
	}
	b.WriteString("\n")

	// Hypothesis verdict block.
	b.WriteString("## Hypothesis Verdict\n\n")
	b.WriteString(renderHypothesis(d))
	b.WriteString("\n\n")

	// Aggregate sections.
	b.WriteString("## Aggregate Metrics\n\n")
	b.WriteString(renderAggregateMetrics(d.Records))
	b.WriteString("\n\n")

	// TOON token saving.
	b.WriteString("## TOON Token Saving\n\n")
	b.WriteString(renderTOONSaving(d.Results))
	b.WriteString("\n\n")

	// Per-fixture table.
	b.WriteString("## Per-Fixture Results\n\n")
	b.WriteString("| ID | Category | Golden | Mono Verdict | Decomp Verdict | Mono Tokens | Decomp Tokens | Latency Mono ms | Latency Decomp ms |\n")
	b.WriteString("|---|---|---|---|---|---|---|---|---|\n")
	for i, rec := range d.Records {
		golden := ""
		if i < len(d.Fixtures) {
			golden = d.Fixtures[i].GoldenStatus
		}
		b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %d | %d | %d | %d |\n",
			rec.ID, rec.Category, golden,
			rec.MonolithicStatus, rec.DecomposedStatus,
			rec.TokensMono, rec.TokensDecomp,
			rec.LatencyMonoMs, rec.LatencyDecompMs))
	}

	return b.String()
}

func renderHypothesis(d reportData) string {
	if len(d.Results) == 0 {
		return "> No fixtures run."
	}

	var monoMatch, decompMatch, total int
	var monoTokens, decompTokens int64
	var monoLatencies, decompLatencies []int64

	for i, r := range d.Results {
		golden := d.Fixtures[i].GoldenStatus
		total++
		if accuracyMatch(r.MonoResult, r.MonoErr, golden) {
			monoMatch++
		}
		if accuracyMatch(r.DecompResult, r.DecompErr, golden) {
			decompMatch++
		}
		monoTokens += int64(totalTokens(r.MonoResult))
		decompTokens += int64(totalTokens(r.DecompResult))
		monoLatencies = append(monoLatencies, r.MonoMs)
		decompLatencies = append(decompLatencies, r.DecompMs)
	}

	monoAcc := pct(monoMatch, total)
	decompAcc := pct(decompMatch, total)
	tokenRatio := ratio(decompTokens, monoTokens)
	latP50Mono := percentile(monoLatencies, 50)
	latP50Decomp := percentile(decompLatencies, 50)
	latRatio := ratio64(latP50Decomp, latP50Mono)

	var lines []string
	lines = append(lines, fmt.Sprintf("- **Accuracy:** monolithic %.0f%%, decomposed %.0f%% (target: decomposed ≥ monolithic)", monoAcc, decompAcc))
	lines = append(lines, fmt.Sprintf("- **Token saving:** decomposed uses %.0f%% of monolithic tokens (target: ≤85%%)", tokenRatio*100))
	lines = append(lines, fmt.Sprintf("- **Latency p50:** mono %dms, decomposed %dms (ratio %.2f×, target ≤1.30×)", latP50Mono, latP50Decomp, latRatio))

	verdict := "✅ HYPOTHESIS SUPPORTED"
	if decompAcc < monoAcc || tokenRatio > 0.85 || latRatio > 1.30 {
		verdict = "⚠️ HYPOTHESIS PARTIALLY SUPPORTED — see metrics below"
	}

	return fmt.Sprintf("> **%s**\n>\n> %s", verdict, strings.Join(lines, "\n> "))
}

func renderAggregateMetrics(records []replayutil.RunRecord) string {
	if len(records) == 0 {
		return "_No records._"
	}
	var monoLat, decompLat []int64
	var monoTok, decompTok int64
	var monoCost, decompCost float64

	for _, r := range records {
		monoLat = append(monoLat, r.LatencyMonoMs)
		decompLat = append(decompLat, r.LatencyDecompMs)
		monoTok += int64(r.TokensMono)
		decompTok += int64(r.TokensDecomp)
		monoCost += r.CostMonoUSD
		decompCost += r.CostDecompUSD
	}

	return fmt.Sprintf(`| Metric | Monolithic | Decomposed | Delta |
|---|---|---|---|
| Latency p50 (ms) | %d | %d | %.1f× |
| Latency p95 (ms) | %d | %d | %.1f× |
| Total tokens | %d | %d | %.0f%% |
| Total cost USD | $%.4f | $%.4f | %.0f%% |`,
		percentile(monoLat, 50), percentile(decompLat, 50),
		ratio64(percentile(decompLat, 50), percentile(monoLat, 50)),
		percentile(monoLat, 95), percentile(decompLat, 95),
		ratio64(percentile(decompLat, 95), percentile(monoLat, 95)),
		monoTok, decompTok, ratio(decompTok, monoTok)*100,
		monoCost, decompCost, ratioF(decompCost, monoCost)*100,
	)
}

func renderTOONSaving(results []benchResult) string {
	if len(results) == 0 {
		return "_No results._"
	}
	var ratios []float64
	for _, r := range results {
		if r.DecompErr == nil && r.DecompResult.Answer.Verdict != "" {
			ratio, err := toonSaving(r.DecompResult.Answer)
			if err == nil {
				ratios = append(ratios, ratio)
			}
		}
	}
	if len(ratios) == 0 {
		return "_No successful decomposed runs._"
	}
	mean := 0.0
	for _, r := range ratios {
		mean += r
	}
	mean /= float64(len(ratios))
	return fmt.Sprintf("Mean TOON/JSON length ratio: **%.0f%%** (target: ≤60%%)", mean*100)
}

// --- helpers ---

func pct(n, total int) float64 {
	if total == 0 {
		return 0
	}
	return float64(n) / float64(total) * 100
}

func ratio(a, b int64) float64 {
	if b == 0 {
		return 1.0
	}
	return float64(a) / float64(b)
}

func ratio64(a, b int64) float64 {
	if b == 0 {
		return 1.0
	}
	return float64(a) / float64(b)
}

func ratioF(a, b float64) float64 {
	if b == 0 {
		return 1.0
	}
	return a / b
}

func percentile(data []int64, p int) int64 {
	if len(data) == 0 {
		return 0
	}
	sorted := make([]int64, len(data))
	copy(sorted, data)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i] < sorted[j] })
	idx := int(math.Ceil(float64(p)/100*float64(len(sorted)))) - 1
	if idx < 0 {
		idx = 0
	}
	return sorted[idx]
}

// Ensure decompose and wsverdict imports compile (used indirectly via runner.go).
var _ = decompose.StatusOK
var _ = wsverdict.FinalVerdict{}
