package extract

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGeneratedCodeDetector_Patterns(t *testing.T) {
	tmpDir := t.TempDir()

	// Create files matching various generated code patterns
	testCases := []struct {
		path     string
		content  string
		reason   string
		expected bool
	}{
		// Filename patterns
		{"file.pb.go", "// proto file", "protobuf_generated", true},
		{"file.pb.ts", "// proto ts", "protobuf_generated", true},
		{"file.gen.go", "// generated", "codegen_generated", true},
		{"file.gen.ts", "// generated ts", "codegen_generated", true},
		{"query.gql.ts", "// graphql", "codegen_generated", true},

		// Directory patterns
		{"__generated__/file.ts", "// generated dir", "directory:__generated__", true},

		// Header markers
		{"generated.go", "// Code generated by tool. DO NOT EDIT.", "header:Code generated by", true},
		{"generated.go", "// DO NOT EDIT", "header:DO NOT EDIT", true},
		{"generated.java", "@Generated annotation", "header:@Generated", true},
		{"generated.py", "# Generated by tool", "header:# Generated by", true},
		{"generated.js", "/* eslint-disable */", "header:eslint-disable", true},

		// Regular files (not generated)
		{"regular.go", "// normal go file", "", false},
		{"regular.ts", "// normal ts file", "", false},
		{"regular.py", "# normal py file", "", false},
	}

	for _, tc := range testCases {
		t.Run(tc.path, func(t *testing.T) {
			fullPath := filepath.Join(tmpDir, tc.path)
			dir := filepath.Dir(fullPath)
			if err := os.MkdirAll(dir, 0755); err != nil {
				t.Fatalf("Failed to create directory: %v", err)
			}
			if err := os.WriteFile(fullPath, []byte(tc.content), 0644); err != nil {
				t.Fatalf("Failed to create file: %v", err)
			}
		})
	}

	detector := GeneratedCodeDetector{}
	frag, err := detector.Extract(context.Background(), tmpDir)
	if err != nil {
		t.Fatalf("Extract failed: %v", err)
	}

	if frag.Generated == nil {
		t.Fatal("Generated files list is nil")
	}

	// Check that expected generated files are detected
	expectedGenerated := []string{
		"file.pb.go",
		"file.pb.ts",
		"file.gen.go",
		"file.gen.ts",
		"query.gql.ts",
		"__generated__/file.ts",
	}

	for _, expectedPath := range expectedGenerated {
		found := false
		for _, gen := range frag.Generated {
			if gen.Path == expectedPath {
				found = true
				if gen.Reason == "" {
					t.Errorf("Generated file %s has empty reason", expectedPath)
				}
				break
			}
		}
		if !found {
			t.Errorf("Expected generated file %s not found", expectedPath)
		}
	}

	// Check that regular files are not flagged as generated
	regularFiles := []string{
		"regular.go",
		"regular.ts",
		"regular.py",
	}

	for _, regularPath := range regularFiles {
		for _, gen := range frag.Generated {
			if gen.Path == regularPath {
				t.Errorf("Regular file %s incorrectly flagged as generated", regularPath)
			}
		}
	}
}

func TestGeneratedCodeDetector_HeaderMarkers(t *testing.T) {
	tmpDir := t.TempDir()

	headerTests := []struct {
		name     string
		content  string
		expected bool
	}{
		{
			name:     "Code generated by",
			content:  "// Code generated by protoc-gen-go. DO NOT EDIT.",
			expected: true,
		},
		{
			name:     "DO NOT EDIT",
			content:  "// DO NOT EDIT\n// Auto-generated by tool",
			expected: true,
		},
		{
			name:     "@Generated",
			content:  "// @Generated by annotation processor",
			expected: true,
		},
		{
			name:     "Python generated",
			content:  "# Generated by mypy-protobuf.  Do not edit",
			expected: true,
		},
		{
			name:     "ESLint disable",
			content:  "/* eslint-disable */\n/* eslint-disable @typescript-eslint */",
			expected: true,
		},
		{
			name:     "Regular comment",
			content:  "// This is a regular file",
			expected: false,
		},
		{
			name:     "No marker",
			content:  "package main",
			expected: false,
		},
	}

	for _, tt := range headerTests {
		t.Run(tt.name, func(t *testing.T) {
			filePath := filepath.Join(tmpDir, tt.name+".go")
			if err := os.WriteFile(filePath, []byte(tt.content), 0644); err != nil {
				t.Fatalf("Failed to create file: %v", err)
			}

			detector := GeneratedCodeDetector{}
			frag, err := detector.Extract(context.Background(), tmpDir)
			if err != nil {
				t.Fatalf("Extract failed: %v", err)
			}

			found := false
			for _, gen := range frag.Generated {
				if strings.Contains(gen.Path, tt.name) {
					found = true
					if !tt.expected && gen.Reason != "" {
						t.Errorf("File %s incorrectly flagged as generated with reason: %s", tt.name, gen.Reason)
					}
					if tt.expected && gen.Reason == "" {
						t.Errorf("File %s should be flagged as generated but has empty reason", tt.name)
					}
					break
				}
			}

			if tt.expected && !found {
				t.Errorf("File %s should be flagged as generated but wasn't", tt.name)
			}
		})
	}
}

func TestGeneratedCodeDetector_SkipDirectories(t *testing.T) {
	tmpDir := t.TempDir()

	// Create generated files in skipped directories
	skipDirs := []string{
		"node_modules/pkg/file.pb.go",
		"vendor/lib/file.gen.go",
		".git/hooks/file.gen.ts",
	}

	for _, path := range skipDirs {
		fullPath := filepath.Join(tmpDir, path)
		dir := filepath.Dir(fullPath)
		if err := os.MkdirAll(dir, 0755); err != nil {
			t.Fatalf("Failed to create directory: %v", err)
		}
		if err := os.WriteFile(fullPath, []byte("// Code generated"), 0644); err != nil {
			t.Fatalf("Failed to create file: %v", err)
		}
	}

	// Create a generated file in a normal directory
	normalGen := filepath.Join(tmpDir, "file.pb.go")
	if err := os.WriteFile(normalGen, []byte("// generated"), 0644); err != nil {
		t.Fatalf("Failed to create file: %v", err)
	}

	detector := GeneratedCodeDetector{}
	frag, err := detector.Extract(context.Background(), tmpDir)
	if err != nil {
		t.Fatalf("Extract failed: %v", err)
	}

	// Should only detect the file in the normal directory
	if len(frag.Generated) != 1 {
		t.Errorf("Expected 1 generated file, got %d", len(frag.Generated))
	}

	if len(frag.Generated) > 0 && frag.Generated[0].Path != "file.pb.go" {
		t.Errorf("Expected file.pb.go, got %s", frag.Generated[0].Path)
	}
}

func TestGeneratedCodeDetector_ContextCancellation(t *testing.T) {
	tmpDir := t.TempDir()

	// Create many files
	for i := 0; i < 100; i++ {
		file := filepath.Join(tmpDir, filepath.Join("dir", "file.pb.go"))
		dir := filepath.Dir(file)
		if err := os.MkdirAll(dir, 0755); err != nil {
			t.Fatalf("Failed to create directory: %v", err)
		}
		if err := os.WriteFile(file, []byte("// generated"), 0644); err != nil {
			t.Fatalf("Failed to create file: %v", err)
		}
	}

	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	detector := GeneratedCodeDetector{}
	_, err := detector.Extract(ctx, tmpDir)
	if err == nil {
		t.Error("Expected error for cancelled context, got nil")
	}
	if err != context.Canceled {
		t.Errorf("Expected context.Canceled error, got %v", err)
	}
}

func TestCheckHeader(t *testing.T) {
	tests := []struct {
		name     string
		content  string
		expected bool
		reason   string
	}{
		{
			name:     "First line marker",
			content:  "// Code generated by tool\npackage main",
			expected: true,
			reason:   "header:Code generated by",
		},
		{
			name:     "Third line marker",
			content:  "// Copyright\n// License\n// DO NOT EDIT\npackage main",
			expected: true,
			reason:   "header:DO NOT EDIT",
		},
		{
			name:     "No marker",
			content:  "package main\n\nfunc main() {}",
			expected: false,
			reason:   "",
		},
		{
			name:     "Marker after 5 lines",
			content:  "// line 1\n// line 2\n// line 3\n// line 4\n// line 5\n// Code generated",
			expected: false, // Only checks first 5 lines
			reason:   "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpFile, err := os.CreateTemp("", "test-*.go")
			if err != nil {
				t.Fatalf("Failed to create temp file: %v", err)
			}
			defer os.Remove(tmpFile.Name())

			if _, err := tmpFile.WriteString(tt.content); err != nil {
				t.Fatalf("Failed to write to temp file: %v", err)
			}
			tmpFile.Close()

			reason, ok := checkHeader(tmpFile.Name())
			if ok != tt.expected {
				t.Errorf("checkHeader() ok = %v, want %v", ok, tt.expected)
			}
			if ok && reason != tt.reason {
				t.Errorf("checkHeader() reason = %q, want %q", reason, tt.reason)
			}
		})
	}
}

func TestGeneratedCodeDetector_AllPatterns(t *testing.T) {
	// Test all patterns mentioned in acceptance criteria
	tmpDir := t.TempDir()

	patterns := []struct {
		path    string
		reason  string
		content string
	}{
		// Header markers
		{"header1.go", "// Code generated by tool"},
		{"header2.go", "// DO NOT EDIT"},
		{"header3.java", "@Generated"},
		{"header4.py", "# Generated by"},
		{"header5.js", "/* eslint-disable */"},

		// Directory patterns
		{"generated/__init__.py", ""},

		// Filename patterns
		{"file.pb.go", ""},
		{"file.pb.ts", ""},
	}

	for _, p := range patterns {
		fullPath := filepath.Join(tmpDir, p.path)
		dir := filepath.Dir(fullPath)
		if err := os.MkdirAll(dir, 0755); err != nil {
			t.Fatalf("Failed to create directory: %v", err)
		}
		content := p.content
		if content == "" {
			content = "// default content"
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			t.Fatalf("Failed to create file %s: %v", p.path, err)
		}
	}

	detector := GeneratedCodeDetector{}
	frag, err := detector.Extract(context.Background(), tmpDir)
	if err != nil {
		t.Fatalf("Extract failed: %v", err)
	}

	expectedCount := len(patterns)
	if len(frag.Generated) != expectedCount {
		t.Errorf("Expected %d generated files, got %d", expectedCount, len(frag.Generated))
	}

	// Verify each pattern was detected
	for _, p := range patterns {
		found := false
		for _, gen := range frag.Generated {
			if gen.Path == p.path {
				found = true
				if gen.Reason == "" {
					t.Errorf("Generated file %s has empty reason", p.path)
				}
				break
			}
		}
		if !found {
			t.Errorf("Pattern %s was not detected as generated", p.path)
		}
	}
}
