package extract

import (
	"bufio"
	"context"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"sdp_dev/internal/architect"
)

// headerMarkers are substrings checked in the first few lines of a file.
// If any line contains one of these, the file is flagged as generated.
var headerMarkers = []string{
	"Code generated by",
	"DO NOT EDIT",
	"@Generated",
}

// generatedPatterns maps filename glob patterns to a reason label.
var generatedPatterns = map[string]string{
	"*.pb.go":  "protobuf_generated",
	"*.gen.go": "codegen_generated",
}

// generatedDirSubstrings flags entire files inside matching directory names.
var generatedDirSubstrings = []string{
	"__generated__",
}

// maxHeaderLines is the number of leading lines inspected for markers.
const maxHeaderLines = 5

// GeneratedCodeDetector identifies files that appear to be machine-generated
// by checking filename patterns, directory names, and file header comments.
type GeneratedCodeDetector struct{}

// Name implements architect.Extractor.
func (GeneratedCodeDetector) Name() string { return "generated" }

// Extract implements architect.Extractor.
func (GeneratedCodeDetector) Extract(ctx context.Context, repoRoot string) (*architect.ProfileFragment, error) {
	var generated []architect.GeneratedFile

	err := filepath.WalkDir(repoRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		if d.IsDir() {
			if skipDirs[d.Name()] {
				return fs.SkipDir
			}
			return nil
		}

		rel, _ := filepath.Rel(repoRoot, path)

		// 1. Check directory name.
		for _, sub := range generatedDirSubstrings {
			if strings.Contains(rel, sub) {
				generated = append(generated, architect.GeneratedFile{
					Path:   rel,
					Reason: "directory:" + sub,
				})
				return nil
			}
		}

		// 2. Check filename pattern.
		base := d.Name()
		for pattern, reason := range generatedPatterns {
			if matched, _ := filepath.Match(pattern, base); matched {
				generated = append(generated, architect.GeneratedFile{
					Path:   rel,
					Reason: reason,
				})
				return nil
			}
		}

		// 3. Check file header for markers (only text-like files).
		if reason, ok := checkHeader(path); ok {
			generated = append(generated, architect.GeneratedFile{
				Path:   rel,
				Reason: reason,
			})
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	return &architect.ProfileFragment{
		Generated: generated,
	}, nil
}

// checkHeader reads the first maxHeaderLines lines and returns a reason
// string if a generation marker is found.
func checkHeader(path string) (string, bool) {
	f, err := os.Open(path)
	if err != nil {
		return "", false
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	for i := 0; i < maxHeaderLines && sc.Scan(); i++ {
		line := sc.Text()
		for _, marker := range headerMarkers {
			if strings.Contains(line, marker) {
				return "header:" + marker, true
			}
		}
	}
	return "", false
}
