apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adapter-workspaces
  namespace: sdp-adapter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # storageClassName omitted: use cluster default
