package manifest

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// allHarnesses is the canonical column order for the parity matrix.
var allHarnesses = []Harness{HarnessClaudeCode, HarnessOpenCode, HarnessCodex, HarnessCursor}

// ParityMatrix returns a markdown document showing per-harness coverage of
// every command, skill, agent, and MCP server. Generated for F141-05; consumed
// by `sdp doctor` to detect drift between manifest and the published doc.
func (m *Manifest) ParityMatrix(now time.Time) string {
	var b strings.Builder
	b.WriteString("<!-- GENERATED by `sdp manifest parity` — do not edit by hand -->\n")
	b.WriteString("<!-- F141-05: source of truth is sdp.manifest.yaml -->\n\n")
	b.WriteString("# Harness Parity Matrix\n\n")
	fmt.Fprintf(&b, "Generated: %s · manifest version `%s` · sdp_version `%s`\n\n",
		now.UTC().Format("2006-01-02"), m.Version, m.SDPVersion)
	b.WriteString("Legend: ✓ supported · — not declared · ⚠ intentional gap (see notes)\n\n")

	manifestHarnesses := m.Harnesses
	if len(manifestHarnesses) == 0 {
		manifestHarnesses = allHarnesses
	}
	cols := filterHarnesses(allHarnesses, manifestHarnesses)

	writeSection(&b, "Commands", cols, commandRows(m.Commands, cols))
	writeSection(&b, "Skills", cols, skillRows(m.Skills, cols))
	writeSection(&b, "Agents", cols, agentRows(m.Agents, cols))
	if len(m.MCPServers) > 0 {
		writeSection(&b, "MCP Servers", cols, mcpRows(m.MCPServers, cols))
	}
	if notes := collectNotes(m); len(notes) > 0 {
		b.WriteString("## Parity notes\n\n")
		for _, n := range notes {
			fmt.Fprintf(&b, "- **%s** — %s\n", n.name, n.note)
		}
		b.WriteString("\n")
	}
	return b.String()
}

type matrixRow struct {
	name string
	cell map[Harness]string
}

func writeSection(b *strings.Builder, title string, cols []Harness, rows []matrixRow) {
	fmt.Fprintf(b, "## %s\n\n", title)
	if len(rows) == 0 {
		b.WriteString("_(none declared)_\n\n")
		return
	}
	b.WriteString("| Name |")
	for _, h := range cols {
		fmt.Fprintf(b, " %s |", h)
	}
	b.WriteString("\n|---|")
	for range cols {
		b.WriteString("---|")
	}
	b.WriteString("\n")
	sort.Slice(rows, func(i, j int) bool { return rows[i].name < rows[j].name })
	for _, r := range rows {
		fmt.Fprintf(b, "| `%s` |", r.name)
		for _, h := range cols {
			cell, ok := r.cell[h]
			if !ok || cell == "" {
				cell = "—"
			}
			fmt.Fprintf(b, " %s |", cell)
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")
}

func commandRows(items []Command, cols []Harness) []matrixRow {
	out := make([]matrixRow, 0, len(items))
	for _, c := range items {
		row := matrixRow{name: c.Name, cell: make(map[Harness]string, len(cols))}
		coverage := harnessSet(c.Harnesses, len(cols))
		for _, h := range cols {
			switch {
			case coverage[h]:
				row.cell[h] = "✓"
			case c.ParityNotes != "":
				row.cell[h] = "⚠"
			default:
				row.cell[h] = "—"
			}
		}
		out = append(out, row)
	}
	return out
}

func skillRows(items []Skill, cols []Harness) []matrixRow {
	out := make([]matrixRow, 0, len(items))
	for _, s := range items {
		row := matrixRow{name: s.Name, cell: make(map[Harness]string, len(cols))}
		coverage := harnessSet(s.Harnesses, len(cols))
		for _, h := range cols {
			if coverage[h] {
				row.cell[h] = "✓"
			} else {
				row.cell[h] = "—"
			}
		}
		out = append(out, row)
	}
	return out
}

func agentRows(items []Agent, cols []Harness) []matrixRow {
	out := make([]matrixRow, 0, len(items))
	for _, a := range items {
		row := matrixRow{name: a.Name, cell: make(map[Harness]string, len(cols))}
		coverage := harnessSet(a.Harnesses, len(cols))
		for _, h := range cols {
			if coverage[h] {
				row.cell[h] = "✓"
			} else {
				row.cell[h] = "—"
			}
		}
		out = append(out, row)
	}
	return out
}

func mcpRows(items []MCPServer, cols []Harness) []matrixRow {
	out := make([]matrixRow, 0, len(items))
	for _, s := range items {
		row := matrixRow{name: s.Name, cell: make(map[Harness]string, len(cols))}
		coverage := harnessSet(s.Harnesses, len(cols))
		for _, h := range cols {
			if coverage[h] {
				if s.Optional {
					row.cell[h] = "○"
				} else {
					row.cell[h] = "✓"
				}
			} else {
				row.cell[h] = "—"
			}
		}
		out = append(out, row)
	}
	return out
}

// harnessSet treats an empty list as "applies to all" per design §3.5: omitting
// `harnesses` means default coverage = all harnesses listed in the manifest's
// top-level `harnesses` field.
func harnessSet(declared []Harness, defaultSize int) map[Harness]bool {
	if len(declared) == 0 {
		out := make(map[Harness]bool, defaultSize)
		for _, h := range allHarnesses {
			out[h] = true
		}
		return out
	}
	out := make(map[Harness]bool, len(declared))
	for _, h := range declared {
		out[h] = true
	}
	return out
}

func filterHarnesses(canonical, requested []Harness) []Harness {
	have := make(map[Harness]bool, len(requested))
	for _, h := range requested {
		have[h] = true
	}
	out := make([]Harness, 0, len(canonical))
	for _, h := range canonical {
		if have[h] {
			out = append(out, h)
		}
	}
	return out
}

type parityNote struct {
	name string
	note string
}

func collectNotes(m *Manifest) []parityNote {
	var out []parityNote
	for _, c := range m.Commands {
		if c.ParityNotes != "" {
			out = append(out, parityNote{name: "command/" + c.Name, note: c.ParityNotes})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}
