package mcp

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/mark3labs/mcp-go/mcp"
)

// resourceDef describes a single .sdp/ artifact resource.
type resourceDef struct {
	uri         string // sdp://<name>
	name        string // Human-readable name
	description string // What this resource provides
	relPath     string // Path relative to repo root (e.g. ".sdp/scout.json")
	mimeType    string // MIME type of the content
	hintTool    string // Tool to suggest when the artifact is missing
}

// staticResources lists always-registered resources with their .sdp/ file paths.
// Resources that do not exist on disk return a helpful error message.
var staticResources = []resourceDef{
	{
		uri:         "sdp://manifest",
		name:        "SDP Manifest",
		description: "Context primer for the repository (markdown, ≤2K tokens). Generated by sdp_index_build.",
		relPath:     ".sdp/manifest.md",
		mimeType:    "text/markdown",
		hintTool:    "sdp_index_build",
	},
	{
		uri:         "sdp://scout",
		name:        "Scout Report",
		description: "Project card with languages, frameworks, structure, and health signals.",
		relPath:     ".sdp/scout.json",
		mimeType:    "application/json",
		hintTool:    "sdp_scout",
	},
	{
		uri:         "sdp://architect",
		name:        "Architecture Report",
		description: "C4 models, dependency graphs, and quality metrics from architecture analysis.",
		relPath:     ".sdp/architecture/report.json",
		mimeType:    "application/json",
		hintTool:    "sdp_architect",
	},
	{
		uri:         "sdp://metrics",
		name:        "Metrics Report",
		description: "Git-derived process health metrics: activity, hygiene, release patterns.",
		relPath:     ".sdp/metrics/report.json",
		mimeType:    "application/json",
		hintTool:    "sdp_metrics",
	},
	{
		uri:         "sdp://spec",
		name:        "Spec Report",
		description: "Recovered API contracts, business rules, invariants, and SLA parameters.",
		relPath:     ".sdp/specs/report.json",
		mimeType:    "application/json",
		hintTool:    "sdp_spec",
	},
	{
		uri:         "sdp://bootstrap",
		name:        "Bootstrap Report",
		description: "Agent-ready setup artifacts report (AGENTS.md, hooks, policies).",
		relPath:     ".sdp/bootstrap-report.json",
		mimeType:    "application/json",
		hintTool:    "sdp_bootstrap",
	},
}

// registerResources registers all .sdp/ artifact resources with the MCP server.
func (s *Server) registerResources() {
	for _, rd := range staticResources {
		rd := rd // capture loop variable
		resource := mcp.NewResource(rd.uri, rd.name,
			mcp.WithResourceDescription(rd.description),
			mcp.WithMIMEType(rd.mimeType),
		)
		s.inner.AddResource(resource, func(ctx context.Context, req mcp.ReadResourceRequest) ([]mcp.ResourceContents, error) {
			return s.handleFileResource(ctx, req, rd)
		})
	}
}

// handleFileResource reads a .sdp/ artifact file and returns it as an MCP resource.
// If the file does not exist, it returns a helpful error message suggesting which
// tool to run to generate it.
func (s *Server) handleFileResource(_ context.Context, req mcp.ReadResourceRequest, rd resourceDef) ([]mcp.ResourceContents, error) {
	absPath := filepath.Join(s.config.RepoRoot, rd.relPath)
	content, err := os.ReadFile(absPath)
	if err != nil {
		hint := fmt.Sprintf(
			"Artifact not found at %s. Run the %q tool first to generate it.",
			rd.relPath, rd.hintTool,
		)
		return []mcp.ResourceContents{
			mcp.TextResourceContents{
				URI:      req.Params.URI,
				MIMEType: "text/plain",
				Text:     hint,
			},
		}, nil
	}
	return []mcp.ResourceContents{
		mcp.TextResourceContents{
			URI:      req.Params.URI,
			MIMEType: rd.mimeType,
			Text:     string(content),
		},
	}, nil
}
