package mcp

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
)

// safeReadFile reads a file at relPath (under repoRoot/.sdp/) after resolving
// symlinks and verifying the resolved path still falls under repoRoot/.sdp/.
// This prevents symlink-based path escapes where a symlink inside .sdp/ points
// outside the repository (e.g. .sdp/scout.json -> ../../.env).
func safeReadFile(repoRoot, relPath string) ([]byte, error) {
	absPath := filepath.Join(repoRoot, relPath)

	// Resolve all symlinks in the path.
	evaluated, err := filepath.EvalSymlinks(absPath)
	if err != nil {
		return nil, fmt.Errorf("resource not available: %s not found — symlink resolution failed: %w", relPath, err)
	}

	// Compute the expected .sdp/ root after symlink resolution.
	sdpRoot := filepath.Join(repoRoot, ".sdp")
	evalSdpRoot, err := filepath.EvalSymlinks(sdpRoot)
	if err != nil {
		// .sdp/ itself may not exist or contain symlinks; fall back to the
		// lexical path.
		evalSdpRoot = filepath.Clean(sdpRoot)
	}

	// Verify the evaluated path is still under .sdp/.
	if !strings.HasPrefix(filepath.Clean(evaluated), filepath.Clean(evalSdpRoot)+string(filepath.Separator)) {
		return nil, fmt.Errorf("resource path escapes .sdp/ boundary after symlink resolution: %s -> %s", relPath, evaluated)
	}

	return os.ReadFile(evaluated)
}

// resourceDef describes a single .sdp/ artifact resource.
type resourceDef struct {
	uri         string // sdp://<name>
	name        string // Human-readable name
	description string // What this resource provides
	relPath     string // Path relative to repo root (e.g. ".sdp/scout.json")
	mimeType    string // MIME type of the content
	hintTool    string // Tool to suggest when the artifact is missing
}

// staticResources lists always-registered resources with their .sdp/ file paths.
// Resources that do not exist on disk return a helpful error message.
//
// Artifact generation contract:
//   - sdp://manifest       — generated by `sdp index build --manifest` (CLI subcommand).
//     The sdp_index_build MCP tool invokes `sdp index build`, which may produce this
//     file as a side effect depending on CLI flags.
//   - sdp://index/modules, sdp://index/stats — planned for future index tool enhancement.
//     Currently no MCP tool produces these files directly; they are registered as
//     forward-compatible resources so that clients can discover them once the CLI
//     gains the capability.
//   - All other resources (scout, architect, metrics, spec, bootstrap) are produced
//     by their corresponding MCP tools via CLI side effects.
var staticResources = []resourceDef{
	{
		uri:         "sdp://manifest",
		name:        "SDP Manifest",
		description: "Context primer for the repository (markdown, <=2K tokens). Generated by `sdp index build --manifest`.",
		relPath:     ".sdp/manifest.md",
		mimeType:    "text/markdown",
		hintTool:    "sdp_index_build",
	},
	{
		uri:         "sdp://scout",
		name:        "Scout Report",
		description: "Project card with languages, frameworks, structure, and health signals.",
		relPath:     ".sdp/scout.json",
		mimeType:    "application/json",
		hintTool:    "sdp_scout",
	},
	{
		uri:         "sdp://architect",
		name:        "Architecture Report",
		description: "C4 models, dependency graphs, and quality metrics from architecture analysis.",
		relPath:     ".sdp/architecture/report.json",
		mimeType:    "application/json",
		hintTool:    "sdp_architect",
	},
	{
		uri:         "sdp://metrics",
		name:        "Metrics Report",
		description: "Git-derived process health metrics: activity, hygiene, release patterns.",
		relPath:     ".sdp/metrics/report.json",
		mimeType:    "application/json",
		hintTool:    "sdp_metrics",
	},
	{
		uri:         "sdp://spec",
		name:        "Spec Report",
		description: "Recovered API contracts, business rules, invariants, and SLA parameters.",
		relPath:     ".sdp/specs/report.json",
		mimeType:    "application/json",
		hintTool:    "sdp_spec",
	},
	{
		uri:         "sdp://bootstrap",
		name:        "Bootstrap Report",
		description: "Agent-ready setup artifacts report (AGENTS.md, hooks, policies).",
		relPath:     ".sdp/bootstrap-report.json",
		mimeType:    "application/json",
		hintTool:    "sdp_bootstrap",
	},
	{
		uri:         "sdp://index/modules",
		name:        "Index Module List",
		description: "Module list with metadata from the codebase index. Planned: will be populated by a future index tool enhancement.",
		relPath:     ".sdp/index/modules.json",
		mimeType:    "application/json",
		hintTool:    "sdp_index_build",
	},
	{
		uri:         "sdp://index/stats",
		name:        "Index Statistics",
		description: "Index statistics: file counts, symbol counts, index freshness. Planned: will be populated by a future index tool enhancement.",
		relPath:     ".sdp/index/stats.json",
		mimeType:    "application/json",
		hintTool:    "sdp_index_build",
	},
}

// registerResources registers all .sdp/ artifact resources with the MCP server.
func (s *Server) registerResources() {
	for _, rd := range staticResources {
		rd := rd // capture loop variable
		resource := mcp.NewResource(rd.uri, rd.name,
			mcp.WithResourceDescription(rd.description),
			mcp.WithMIMEType(rd.mimeType),
		)
		s.inner.AddResource(resource, func(ctx context.Context, req mcp.ReadResourceRequest) ([]mcp.ResourceContents, error) {
			return s.handleFileResource(ctx, req, rd)
		})
	}
}

// handleFileResource reads a .sdp/ artifact file and returns it as an MCP resource.
// If the file does not exist, it returns an MCP error indicating which tool to run.
//
// Artifact contract: Resources reflect state generated by prior tool invocations
// (or direct CLI usage). If a tool has not been run, the corresponding resource
// will not be available. The MCP tools wrap CLI commands; it is the CLI's
// responsibility to produce artifacts on disk. Running a tool (e.g. sdp_scout)
// generates the file that the matching resource (e.g. sdp://scout) reads.
func (s *Server) handleFileResource(_ context.Context, req mcp.ReadResourceRequest, rd resourceDef) ([]mcp.ResourceContents, error) {
	// Defense in depth: verify the hardcoded relPath stays within .sdp/.
	cleaned := filepath.Clean(rd.relPath)
	if !strings.HasPrefix(cleaned, ".sdp/") {
		return nil, fmt.Errorf("resource path escapes .sdp/ boundary: %s", rd.relPath)
	}

	content, err := safeReadFile(s.config.RepoRoot, rd.relPath)
	if err != nil {
		// Propagate symlink escape errors as-is (they contain security-relevant
		// diagnostics). Wrap all other errors (file not found, etc.) with a
		// hint about which tool to run.
		if strings.Contains(err.Error(), "escapes .sdp/") {
			return nil, err
		}
		return nil, fmt.Errorf("resource not available: %s not found — run %s to generate it", rd.relPath, rd.hintTool)
	}
	return []mcp.ResourceContents{
		mcp.TextResourceContents{
			URI:      req.Params.URI,
			MIMEType: rd.mimeType,
			Text:     string(content),
		},
	}, nil
}
