package bootstrap

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// --- Fresh generation tests ---

func TestGenerateAgentsMD_Fresh(t *testing.T) {
	dir := t.TempDir()
	ds := DataSourceInfo{
		Scout: &ScoutData{
			PrimaryLanguage: "Go",
			BuildSystem:     "go",
		},
	}
	cmds := BuildCommands{
		Build: "go build ./...",
		Test:  "go test ./...",
		Lint:  "golangci-lint run",
	}

	result, err := GenerateAgentsMD(dir, ds, cmds)
	require.NoError(t, err)

	// Verify structure.
	assert.Contains(t, result, "# Agent Coordination for "+filepath.Base(dir))
	assert.Contains(t, result, "## Available Agents")
	assert.Contains(t, result, "## Shared Conventions")
	assert.Contains(t, result, "## Agent-Specific Notes")

	// Verify default agents.
	assert.Contains(t, result, "Claude Code")
	assert.Contains(t, result, "Codex CLI")
	assert.Contains(t, result, "Cursor")

	// Verify generated markers (named markers).
	assert.Contains(t, result, "<!-- generated by sdp bootstrap: Available Agents -->")
	assert.Contains(t, result, "<!-- end generated by sdp bootstrap -->")

	// Verify shared conventions.
	assert.Contains(t, result, "Conventional commits")
	assert.Contains(t, result, "tests before committing")
}

func TestGenerateAgentsMD_WithTestCommand(t *testing.T) {
	dir := t.TempDir()
	ds := DataSourceInfo{
		Scout: &ScoutData{
			PrimaryLanguage: "Go",
			BuildSystem:     "go",
			HasCI:           true,
			CISystem:        "github",
		},
	}
	cmds := BuildCommands{
		Build: "go build ./...",
		Test:  "go test ./...",
		Lint:  "golangci-lint run",
	}

	result, err := GenerateAgentsMD(dir, ds, cmds)
	require.NoError(t, err)

	assert.Contains(t, result, "go test ./...")
	assert.Contains(t, result, "golangci-lint run")
	assert.Contains(t, result, "github")
}

func TestGenerateAgentsMD_NoDataSource(t *testing.T) {
	dir := t.TempDir()
	ds := DataSourceInfo{}
	cmds := BuildCommands{}

	result, err := GenerateAgentsMD(dir, ds, cmds)
	require.NoError(t, err)

	// Should produce output with defaults.
	assert.Contains(t, result, "# Agent Coordination for")
	assert.Contains(t, result, "## Available Agents")
	assert.Contains(t, result, "Claude Code")
}

func TestGenerateAgentsMD_PythonProject(t *testing.T) {
	dir := t.TempDir()
	ds := DataSourceInfo{
		Scout: &ScoutData{
			PrimaryLanguage: "Python",
			BuildSystem:     "setuptools",
		},
	}
	cmds := BuildCommands{
		Build: "python -m build",
		Test:  "pytest",
		Lint:  "ruff check",
	}

	result, err := GenerateAgentsMD(dir, ds, cmds)
	require.NoError(t, err)

	assert.Contains(t, result, "Python")
	assert.Contains(t, result, "pytest")
}

func TestGenerateAgentsMD_SingleMaintainer(t *testing.T) {
	dir := t.TempDir()
	ds := DataSourceInfo{
		Scout:   &ScoutData{PrimaryLanguage: "Go", BuildSystem: "go"},
		Metrics: &MetricsData{BusFactor: 1},
	}
	cmds := BuildCommands{Build: "go build ./...", Test: "go test ./...", Lint: "golangci-lint run"}

	result, err := GenerateAgentsMD(dir, ds, cmds)
	require.NoError(t, err)

	assert.Contains(t, result, "direct to main")
}

// --- Merge tests ---

func TestMergeAgentsMD_FreshMerge(t *testing.T) {
	dir := t.TempDir()
	existing := `# My Custom Agents Config

## Custom Agent Rules

My custom rules here.

## My Workflow

Custom workflow details.
`
	ds := DataSourceInfo{
		Scout: &ScoutData{PrimaryLanguage: "Go", BuildSystem: "go"},
	}
	cmds := BuildCommands{Build: "go build ./...", Test: "go test ./...", Lint: "golangci-lint run"}

	result, err := MergeAgentsMD(existing, dir, ds, cmds)
	require.NoError(t, err)

	// User content must be preserved.
	assert.Contains(t, result, "My Custom Agents Config")
	assert.Contains(t, result, "## Custom Agent Rules")
	assert.Contains(t, result, "My custom rules here.")
	assert.Contains(t, result, "## My Workflow")
	assert.Contains(t, result, "Custom workflow details.")

	// Generated sections should be added.
	assert.Contains(t, result, "<!-- generated by sdp bootstrap:")
}

func TestMergeAgentsMD_ExistingGeneratedSections(t *testing.T) {
	dir := t.TempDir()
	existing := `# My Project

My intro.

<!-- generated by sdp bootstrap: Available Agents -->
## Available Agents

- **OldAgent** — Old description
<!-- end generated by sdp bootstrap -->

## Custom Section

My custom content.
`
	ds := DataSourceInfo{
		Scout: &ScoutData{PrimaryLanguage: "Go", BuildSystem: "go"},
	}
	cmds := BuildCommands{Build: "go build ./...", Test: "go test ./...", Lint: "golangci-lint run"}

	result, err := MergeAgentsMD(existing, dir, ds, cmds)
	require.NoError(t, err)

	// User content preserved.
	assert.Contains(t, result, "My intro.")
	assert.Contains(t, result, "## Custom Section")
	assert.Contains(t, result, "My custom content.")

	// Generated section updated.
	assert.Contains(t, result, "Claude Code")
	assert.Contains(t, result, "<!-- generated by sdp bootstrap: Available Agents -->")
}

func TestMergeAgentsMD_UserContentNeverDeleted(t *testing.T) {
	dir := t.TempDir()
	existing := `# Agents

> Critical hand-written agent coordination rules.

## My Special Agent

- Rule 1: Always use feature branches
- Rule 2: Never push on Fridays
- Rule 3: Review all changes before merge

### Important Sub-rules

More details.
`
	ds := DataSourceInfo{
		Scout: &ScoutData{PrimaryLanguage: "Go", BuildSystem: "go"},
	}
	cmds := BuildCommands{Build: "go build ./...", Test: "go test ./...", Lint: "golangci-lint run"}

	result, err := MergeAgentsMD(existing, dir, ds, cmds)
	require.NoError(t, err)

	assert.Contains(t, result, "Critical hand-written agent coordination rules.")
	assert.Contains(t, result, "Never push on Fridays")
	assert.Contains(t, result, "Review all changes before merge")
	assert.Contains(t, result, "### Important Sub-rules")
}

// --- Integration tests via Planner ---

func TestPlanner_Execute_GeneratesAgentsMD(t *testing.T) {
	dir := setupRepoWithScout(t)

	planner := NewPlanner(BootstrapConfig{RepoPath: dir, NoVerify: true})
	report, err := planner.Execute()
	require.NoError(t, err)

	agentsPath := filepath.Join(dir, "AGENTS.md")
	assert.FileExists(t, agentsPath)

	content, err := os.ReadFile(agentsPath)
	require.NoError(t, err)

	assert.Contains(t, string(content), "<!-- generated by sdp bootstrap: Available Agents -->")
	assert.Contains(t, string(content), "## Available Agents")
	assert.Contains(t, string(content), "Claude Code")

	var found bool
	for _, a := range report.Artifacts {
		if a.Type == "agents_md" {
			found = true
			assert.Equal(t, "ok", a.Status)
		}
	}
	assert.True(t, found)
}

func TestPlanner_Execute_ForceMerge_AgentsMD(t *testing.T) {
	dir := setupRepoWithScout(t)
	existing := "# My Agents\n\nMy custom intro.\n"
	require.NoError(t, os.WriteFile(filepath.Join(dir, "AGENTS.md"), []byte(existing), 0o644))

	planner := NewPlanner(BootstrapConfig{RepoPath: dir, Force: true, NoVerify: true})
	report, err := planner.Execute()
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	require.NoError(t, err)

	assert.Contains(t, string(content), "My custom intro.")
	assert.Contains(t, string(content), "<!-- generated by sdp bootstrap:")

	var found bool
	for _, a := range report.Artifacts {
		if a.Type == "agents_md" && a.Action == "merge" {
			found = true
			assert.Equal(t, "ok", a.Status)
		}
	}
	assert.True(t, found)
}

// --- Helper tests ---

func TestDefaultAgents(t *testing.T) {
	agents := defaultAgents()
	assert.Len(t, agents, 4)

	names := make(map[string]bool)
	for _, a := range agents {
		names[a.Name] = true
		assert.NotEmpty(t, a.Description)
		assert.NotEmpty(t, a.BestFor)
		assert.NotEmpty(t, a.ConfigPath)
	}

	assert.True(t, names["Claude Code"])
	assert.True(t, names["Codex CLI"])
	assert.True(t, names["Cursor"])
	assert.True(t, names["OpenCode"])
}

func TestBuildAgentNotes(t *testing.T) {
	ds := DataSourceInfo{
		Scout: &ScoutData{PrimaryLanguage: "Go", HasCI: true, CISystem: "github"},
	}
	cmds := BuildCommands{Build: "go build ./...", Test: "go test ./...", Lint: "golangci-lint run"}

	notes := buildAgentNotes(ds, cmds)
	assert.NotEmpty(t, notes)

	// Should have Claude, Codex, and All Agents notes.
	var foundClaude, foundCodex, foundAll bool
	for _, n := range notes {
		switch n.Agent {
		case "Claude Code":
			foundClaude = true
		case "Codex CLI":
			foundCodex = true
		case "All Agents":
			foundAll = true
		}
	}
	assert.True(t, foundClaude)
	assert.True(t, foundCodex)
	assert.True(t, foundAll)
}

func TestDetectBranchPattern(t *testing.T) {
	metrics := &MetricsData{BusFactor: 3}
	assert.Contains(t, detectBranchPattern(metrics), "feature/")

	metrics = &MetricsData{BusFactor: 1}
	assert.Contains(t, detectBranchPattern(metrics), "direct to main")
}
