package bootstrap

import (
	"bufio"
	"bytes"
	"embed"
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

//go:embed templates/claude_md.tmpl
var claudeMDTemplateFS embed.FS

// sectionMarkerRegex matches the generated section markers:
//   <!-- generated by sdp bootstrap: Section Name -->
//   ## Section Name
//   ...
//   <!-- end generated by sdp bootstrap -->
var sectionMarkerRegex = regexp.MustCompile(
	`(?s)<!-- generated by sdp bootstrap: (.+?) -->\s*\n(## .+?)\n<!-- end generated by sdp bootstrap -->`)

// GenerateClaudeMD produces a complete CLAUDE.md from the collected data sources.
// It uses the embedded template and falls back gracefully when optional data is missing.
func GenerateClaudeMD(repoPath string, ds DataSourceInfo, cmds BuildCommands) (string, error) {
	data := buildClaudeMDData(repoPath, ds, cmds)

	tmpl, err := parseClaudeMDTemplate()
	if err != nil {
		return "", fmt.Errorf("claude_md: parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("claude_md: execute template: %w", err)
	}

	return strings.TrimSpace(buf.String()) + "\n", nil
}

// MergeClaudeMD merges generated content into an existing CLAUDE.md.
// User-authored sections are preserved. Generated sections are marked with
// HTML comments so they can be safely updated in future runs.
//
// Merge strategy:
//  1. Parse existing CLAUDE.md into sections (by ## headers)
//  2. For each generated section:
//     a. If section exists and content differs, replace only generated blocks
//     b. If section is new, append at the appropriate position
//  3. Never delete user-written content outside generated markers
func MergeClaudeMD(existing string, repoPath string, ds DataSourceInfo, cmds BuildCommands) (string, error) {
	generated, err := GenerateClaudeMD(repoPath, ds, cmds)
	if err != nil {
		return "", err
	}

	// Extract generated sections from the newly generated content.
	genSections := extractGeneratedSections(generated)

	// Replace only the generated blocks within the existing content.
	result := existing

	for name, content := range genSections {
		marker := sectionMarker(name)
		markerRegex := sectionMarkerRegexForName(name)

		if markerRegex.MatchString(result) {
			// Replace existing generated block for this section.
			result = markerRegex.ReplaceAllString(result, marker+"\n"+content+"\n"+endMarker())
		} else {
			// Section is new — find the right insertion point.
			result = insertSection(result, name, content)
		}
	}

	return result, nil
}

// parseClaudeMDTemplate parses the embedded CLAUDE.md template.
func parseClaudeMDTemplate() (*template.Template, error) {
	raw, err := claudeMDTemplateFS.ReadFile("templates/claude_md.tmpl")
	if err != nil {
		return nil, fmt.Errorf("read embedded template: %w", err)
	}
	return template.New("claude_md").Parse(string(raw))
}

// buildClaudeMDData assembles the template data from all available sources.
func buildClaudeMDData(repoPath string, ds DataSourceInfo, cmds BuildCommands) ClaudeMDTemplateData {
	name := filepath.Base(repoPath)
	data := ClaudeMDTemplateData{
		Name:            name,
		Description:     fmt.Sprintf("Project instructions for %s", name),
		PrimaryLanguage: "unknown",
		BuildSystem:     "unknown",
		BuildCommand:    cmds.Build,
		TestCommand:     cmds.Test,
		LintCommand:     cmds.Lint,
		RunCommand:      "",
		ArchSummary:     "Project structure analysis not available.",
		CommitStyle:     "Conventional commits recommended",
		GitFlow:         "Feature branches with PR reviews",
		TestPattern:     "Standard test files (*_test.go, *.test.ts, test_*.py)",
		ErrorPattern:    "Explicit error handling with wrapped errors",
		Antipatterns:    defaultAntipatterns(),
	}

	// Populate from scout (required source, but may be nil in tests).
	if ds.Scout != nil {
		data.PrimaryLanguage = ds.Scout.PrimaryLanguage
		if ds.Scout.BuildSystem != "" {
			data.BuildSystem = ds.Scout.BuildSystem
		}
		if ds.Scout.CISystem != "" {
			data.CISystem = ds.Scout.CISystem
		}
		data.LanguageVersion = detectLanguageVersion(ds.Scout)
		data.TestPattern = detectTestPattern(ds.Scout)
		data.Description = fmt.Sprintf("Project instructions for %s (%s project)", name, ds.Scout.PrimaryLanguage)
	}

	// Enhance from architect data.
	if ds.Architect != nil {
		data.ArchSummary = buildArchSummary(ds.Architect)
		data.Modules = buildModuleList(ds)
		data.ErrorPattern = detectErrorPattern(ds.Architect)
	}

	// Enhance from metrics data.
	if ds.Metrics != nil {
		data.CommitStyle = detectCommitStyle(ds.Metrics)
		data.GitFlow = detectGitFlow(ds.Metrics)
	}

	// Enhance antipatterns from metrics and/or architect data.
	if ds.Metrics != nil || ds.Architect != nil {
		data.Antipatterns = buildAntipatterns(ds)
	}

	// Set run command based on language.
	data.RunCommand = detectRunCommand(data.PrimaryLanguage, cmds)

	return data
}

// detectLanguageVersion returns a version string if detectable from scout data.
func detectLanguageVersion(scout *ScoutData) string {
	// ScoutData does not have explicit version; return empty to indicate unknown.
	return ""
}

// detectTestPattern returns the test pattern based on the primary language.
func detectTestPattern(scout *ScoutData) string {
	switch strings.ToLower(scout.PrimaryLanguage) {
	case "go":
		return "Go standard testing (*_test.go files, go test ./...)"
	case "javascript", "typescript", "node":
		return "Jest/Vitest test files (*.test.ts, *.spec.ts)"
	case "python":
		return "pytest test files (test_*.py, *_test.py)"
	case "rust":
		return "Rust built-in tests (#[test] annotations, cargo test)"
	case "java":
		return "JUnit test files (*Test.java, *Tests.java)"
	default:
		return "Standard test files matching project conventions"
	}
}

// detectErrorPattern returns the error handling pattern based on architecture.
func detectErrorPattern(arch *ArchitectData) string {
	for _, p := range arch.Patterns {
		switch strings.ToLower(p) {
		case "hexagonal", "clean-architecture", "ports-and-adapters":
			return "Domain errors wrapped at adapter boundaries"
		case "microservices", "service-oriented":
			return "Error codes with retry semantics at service boundaries"
		case "event-driven", "event-sourcing":
			return "Dead-letter queues with circuit breaker pattern"
		}
	}
	return "Explicit error handling with wrapped errors"
}

// detectRunCommand returns the run command based on language and build commands.
func detectRunCommand(lang string, cmds BuildCommands) string {
	switch strings.ToLower(lang) {
	case "go":
		return "go run ./..."
	case "javascript", "typescript", "node":
		return "npm start"
	case "python":
		return "python -m <module>"
	case "rust":
		return "cargo run"
	case "java":
		return "mvn exec:java"
	default:
		if cmds.Build != "" {
			return cmds.Build
		}
		return "make run"
	}
}

// detectCommitStyle infers commit style from metrics.
func detectCommitStyle(metrics *MetricsData) string {
	if metrics.ChurnRatio > 0.5 {
		return "Conventional commits strongly recommended (high churn detected)"
	}
	if metrics.CommitFreq == "high" {
		return "Conventional commits (active development)"
	}
	return "Conventional commits recommended"
}

// detectGitFlow infers the git branching model from metrics.
func detectGitFlow(metrics *MetricsData) string {
	if metrics.BusFactor == 1 {
		return "Single maintainer — direct commits to main acceptable, feature branches preferred"
	}
	return "Feature branches with PR reviews"
}

// buildArchSummary builds the architecture summary from architect data.
func buildArchSummary(arch *ArchitectData) string {
	var sb strings.Builder

	if len(arch.Patterns) > 0 {
		sb.WriteString(fmt.Sprintf("Architecture style: %s.", strings.Join(arch.Patterns, ", ")))
	} else {
		sb.WriteString("Standard project layout.")
	}

	if len(arch.Components) > 0 {
		sb.WriteString(fmt.Sprintf(" Components: %s.", strings.Join(arch.Components, ", ")))
	}

	if len(arch.Decisions) > 0 {
		sb.WriteString(fmt.Sprintf(" %d architecture decision(s) recorded.", len(arch.Decisions)))
	}

	return sb.String()
}

// buildModuleList builds the module list from available data sources.
func buildModuleList(ds DataSourceInfo) []ModuleInfo {
	if ds.Architect == nil {
		return nil
	}

	var modules []ModuleInfo
	for _, comp := range ds.Architect.Components {
		modules = append(modules, ModuleInfo{
			Path:    comp,
			Purpose: describeComponent(comp),
			LOC:     0, // Unknown without index
			Owner:   "", // Unknown without metrics
		})
	}

	// Enhance with index data if available.
	if ds.Index != nil {
		for i := range modules {
			if ds.Index.Files > 0 {
				modules[i].LOC = ds.Index.Files / max(len(modules), 1)
			}
		}
	}

	return modules
}

// describeComponent returns a human-readable description of a component path.
func describeComponent(path string) string {
	parts := strings.Split(strings.TrimPrefix(path, "./"), "/")
	if len(parts) == 0 {
		return "Project component"
	}

	base := parts[len(parts)-1]
	prefix := ""
	if len(parts) > 1 {
		prefix = parts[0]
	}

	descriptions := map[string]string{
		"cmd":       "CLI entrypoints",
		"internal":  "Internal packages",
		"pkg":       "Public packages",
		"api":       "API definitions",
		"web":       "Web frontend",
		"ui":        "User interface",
		"docs":      "Documentation",
		"scripts":   "Build and utility scripts",
		"configs":   "Configuration files",
		"migrations": "Database migrations",
		"models":    "Data models",
		"services":  "Service layer",
		"handlers":  "Request handlers",
		"middleware": "HTTP/gRPC middleware",
		"store":     "Data storage layer",
		"repo":      "Repository layer",
		"scout":     "Code analysis and discovery",
		"bootstrap": "Project bootstrapping and scaffolding",
	}

	if desc, ok := descriptions[base]; ok {
		return desc
	}
	if desc, ok := descriptions[prefix]; ok {
		return desc + " — " + base
	}
	return base + " module"
}

// defaultAntipatterns returns language-agnostic antipatterns.
func defaultAntipatterns() []string {
	return []string{
		"Do not commit directly to main — use feature branches",
		"Do not skip tests before pushing",
		"Do not hardcode secrets or credentials",
		"Do not ignore lint warnings without documented justification",
	}
}

// buildAntipatterns builds project-specific antipatterns from metrics and architect data.
func buildAntipatterns(ds DataSourceInfo) []string {
	antipatterns := defaultAntipatterns()

	if ds.Metrics != nil {
		if ds.Metrics.BusFactor == 1 {
			antipatterns = append(antipatterns, "Bus factor is 1 — ensure knowledge sharing across the team")
		}
		if ds.Metrics.Staleness == "stale" || ds.Metrics.Staleness == "high" {
			antipatterns = append(antipatterns, "High code staleness detected — review and refactor neglected areas")
		}
		if ds.Metrics.ChurnRatio > 0.5 {
			antipatterns = append(antipatterns, "High churn ratio — stabilize frequently changing modules")
		}
	}

	if ds.Architect != nil {
		for _, d := range ds.Architect.Decisions {
			if d.Status == "deprecated" || d.Status == "superseded" {
				antipatterns = append(antipatterns, fmt.Sprintf("Respect %s (%s): %s", d.ID, d.Status, d.Title))
			}
		}
	}

	return antipatterns
}

// --- Merge helpers ---

// sectionMarker returns the opening HTML comment for a generated section.
func sectionMarker(name string) string {
	return fmt.Sprintf("<!-- generated by sdp bootstrap: %s -->", name)
}

// endMarker returns the closing HTML comment for a generated section.
func endMarker() string {
	return "<!-- end generated by sdp bootstrap -->"
}

// sectionMarkerRegexForName returns a regex that matches a generated section block by name.
func sectionMarkerRegexForName(name string) *regexp.Regexp {
	pattern := fmt.Sprintf(
		`(?s)<!-- generated by sdp bootstrap: %s -->\s*\n(## .+?)\n<!-- end generated by sdp bootstrap -->`,
		regexp.QuoteMeta(name))
	return regexp.MustCompile(pattern)
}

// extractGeneratedSections extracts named sections from freshly generated content.
// Returns a map of section name to section body (including the ## header line).
func extractGeneratedSections(content string) map[string]string {
	sections := make(map[string]string)

	// Match all generated blocks with named markers in the content.
	re := regexp.MustCompile(
		`(?s)<!-- generated by sdp bootstrap: (.+?) -->\s*\n(## .+?)\n<!-- end generated by sdp bootstrap -->`)

	matches := re.FindAllStringSubmatch(content, -1)
	for _, m := range matches {
		if len(m) < 3 {
			continue
		}
		name := m[1]
		body := m[2]
		if name != "" {
			sections[name] = body
		}
	}

	return sections
}

// extractSectionName extracts the section name from a ## header line.
func extractSectionName(sectionContent string) string {
	scanner := bufio.NewScanner(strings.NewReader(sectionContent))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "## ") {
			return strings.TrimPrefix(line, "## ")
		}
	}
	return ""
}

// insertSection adds a new section to the existing content at the appropriate position.
// It inserts before the first user-authored section or appends at the end.
func insertSection(existing string, name string, content string) string {
	marker := sectionMarker(name)
	newBlock := fmt.Sprintf("%s\n%s\n%s", marker, content, endMarker())

	// Find all ## headers in existing content.
	sectionPositions := findSectionPositions(existing)

	// If no existing sections, just append.
	if len(sectionPositions) == 0 {
		return existing + "\n" + newBlock + "\n"
	}

	// Define the canonical section order for CLAUDE.md.
	canonicalOrder := []string{
		"Tech Stack", "Architecture", "Conventions", "Commands",
		"What NOT to Do", "Quick Start", "Quality Gates",
	}

	// Find where to insert this section.
	insertIdx := -1
	for i, canonical := range canonicalOrder {
		if canonical == name && i < len(canonicalOrder)-1 {
			// Look for the next canonical section that exists in the document.
			for j := i + 1; j < len(canonicalOrder); j++ {
				nextName := canonicalOrder[j]
				for _, posEntry := range sectionPositions {
					if posEntry.name == nextName {
						if insertIdx == -1 || posEntry.pos < insertIdx {
							insertIdx = posEntry.pos
						}
					}
				}
			}
			break
		}
	}

	if insertIdx == -1 {
		// Append at end.
		return existing + "\n" + newBlock + "\n"
	}

	// Insert before the found position.
	return existing[:insertIdx] + newBlock + "\n\n" + existing[insertIdx:]
}

// findSectionPositions returns the byte offsets and names of all ## sections in the content.
func findSectionPositions(content string) []struct {
	pos  int
	name string
} {
	var positions []struct {
		pos  int
		name string
	}

	scanner := bufio.NewScanner(strings.NewReader(content))
	offset := 0
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "## ") {
			name := strings.TrimPrefix(trimmed, "## ")
			positions = append(positions, struct {
				pos  int
				name string
			}{pos: offset, name: name})
		}
		offset += len(line) + 1 // +1 for newline
	}

	return positions
}
