package bootstrap

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// --- Fresh generation tests ---

func TestGenerateClaudeMD_Fresh_GoProject(t *testing.T) {
	dir := t.TempDir()
	ds := DataSourceInfo{
		Scout: &ScoutData{
			PrimaryLanguage: "Go",
			BuildSystem:     "go",
			HasTests:        true,
			TestRatio:       0.5,
			CISystem:        "github",
		},
	}
	cmds := BuildCommands{
		Build: "go build ./...",
		Test:  "go test ./...",
		Lint:  "golangci-lint run",
	}

	result, err := GenerateClaudeMD(dir, ds, cmds)
	require.NoError(t, err)

	// Verify structure.
	assert.Contains(t, result, "# "+filepath.Base(dir))
	assert.Contains(t, result, "## Tech Stack")
	assert.Contains(t, result, "## Architecture")
	assert.Contains(t, result, "## Conventions")
	assert.Contains(t, result, "## Commands")
	assert.Contains(t, result, "## What NOT to Do")

	// Verify language-specific content.
	assert.Contains(t, result, "Go")
	assert.Contains(t, result, "go build")
	assert.Contains(t, result, "go test")
	assert.Contains(t, result, "golangci-lint run")

	// Verify generated markers (named markers).
	assert.Contains(t, result, "<!-- generated by sdp bootstrap: Tech Stack -->")
	assert.Contains(t, result, "<!-- end generated by sdp bootstrap -->")
}

func TestGenerateClaudeMD_Fresh_PythonProject(t *testing.T) {
	dir := t.TempDir()
	ds := DataSourceInfo{
		Scout: &ScoutData{
			PrimaryLanguage: "Python",
			BuildSystem:     "setuptools",
			HasTests:        true,
		},
	}
	cmds := BuildCommands{
		Build: "python -m build",
		Test:  "pytest",
		Lint:  "ruff check",
	}

	result, err := GenerateClaudeMD(dir, ds, cmds)
	require.NoError(t, err)

	assert.Contains(t, result, "Python")
	assert.Contains(t, result, "pytest")
	assert.Contains(t, result, "ruff check")
	assert.Contains(t, result, "python -m build")
}

func TestGenerateClaudeMD_Fresh_NodeProject(t *testing.T) {
	dir := t.TempDir()
	ds := DataSourceInfo{
		Scout: &ScoutData{
			PrimaryLanguage: "TypeScript",
			BuildSystem:     "npm",
			HasTests:        true,
		},
	}
	cmds := BuildCommands{
		Build: "npm run build",
		Test:  "npm test",
		Lint:  "npm run lint",
	}

	result, err := GenerateClaudeMD(dir, ds, cmds)
	require.NoError(t, err)

	assert.Contains(t, result, "TypeScript")
	assert.Contains(t, result, "npm run build")
	assert.Contains(t, result, "npm test")
}

func TestGenerateClaudeMD_FullData(t *testing.T) {
	dir := t.TempDir()
	ds := DataSourceInfo{
		Scout: &ScoutData{
			PrimaryLanguage: "Go",
			BuildSystem:     "go",
			HasTests:        true,
			CISystem:        "github",
			TestRatio:       0.45,
		},
		Architect: &ArchitectData{
			Components: []string{"cmd/server", "internal/api", "internal/store"},
			Decisions: []ArchDecision{
				{ID: "ADR-001", Title: "Use Go", Status: "accepted", Summary: "Go for performance"},
				{ID: "ADR-002", Title: "Use PostgreSQL", Status: "accepted", Summary: "PG for persistence"},
			},
			Patterns: []string{"hexagonal"},
		},
		Metrics: &MetricsData{
			BusFactor:      2,
			CommitFreq:     "high",
			Staleness:      "active",
			ChurnRatio:     0.3,
			TestCovHint:    "~60%",
			ComplexityHint: "moderate",
		},
		Index: &IndexData{
			Symbols:  500,
			Files:    45,
			Language: "Go",
		},
	}
	cmds := BuildCommands{
		Build: "go build ./...",
		Test:  "go test ./...",
		Lint:  "golangci-lint run",
	}

	result, err := GenerateClaudeMD(dir, ds, cmds)
	require.NoError(t, err)

	// Verify full data enhancements.
	assert.Contains(t, result, "hexagonal")
	assert.Contains(t, result, "cmd/server")
	assert.Contains(t, result, "internal/api")
	assert.Contains(t, result, "internal/store")
	assert.Contains(t, result, "github")
	assert.Contains(t, result, "2 architecture decision(s)")
	assert.Contains(t, result, "Domain errors wrapped at adapter boundaries")
}

func TestGenerateClaudeMD_ScoutOnly(t *testing.T) {
	dir := t.TempDir()
	ds := DataSourceInfo{
		Scout: &ScoutData{
			PrimaryLanguage: "Go",
			BuildSystem:     "go",
		},
	}
	cmds := BuildCommands{
		Build: "go build ./...",
		Test:  "go test ./...",
		Lint:  "golangci-lint run",
	}

	result, err := GenerateClaudeMD(dir, ds, cmds)
	require.NoError(t, err)

	// Should still produce valid output with defaults.
	assert.Contains(t, result, "# "+filepath.Base(dir))
	assert.Contains(t, result, "## Tech Stack")
	assert.Contains(t, result, "## Conventions")
	assert.Contains(t, result, "Project structure analysis not available")
	assert.Contains(t, result, "Conventional commits recommended")
}

func TestGenerateClaudeMD_NoDataSource(t *testing.T) {
	dir := t.TempDir()
	ds := DataSourceInfo{}
	cmds := BuildCommands{
		Build: "make build",
		Test:  "make test",
		Lint:  "make lint",
	}

	result, err := GenerateClaudeMD(dir, ds, cmds)
	require.NoError(t, err)

	// Should produce output with defaults.
	assert.Contains(t, result, "# "+filepath.Base(dir))
	assert.Contains(t, result, "unknown")
}

func TestGenerateClaudeMD_MetricsAntipatterns(t *testing.T) {
	dir := t.TempDir()
	ds := DataSourceInfo{
		Scout: &ScoutData{PrimaryLanguage: "Go", BuildSystem: "go"},
		Metrics: &MetricsData{
			BusFactor:  1,
			Staleness:  "stale",
			ChurnRatio: 0.8,
		},
	}
	cmds := BuildCommands{Build: "go build ./...", Test: "go test ./...", Lint: "golangci-lint run"}

	result, err := GenerateClaudeMD(dir, ds, cmds)
	require.NoError(t, err)

	assert.Contains(t, result, "Bus factor is 1")
	assert.Contains(t, result, "High code staleness detected")
	assert.Contains(t, result, "High churn ratio")
}

func TestGenerateClaudeMD_DeprecatedDecisions(t *testing.T) {
	dir := t.TempDir()
	ds := DataSourceInfo{
		Scout: &ScoutData{PrimaryLanguage: "Go", BuildSystem: "go"},
		Architect: &ArchitectData{
			Decisions: []ArchDecision{
				{ID: "ADR-001", Title: "Old approach", Status: "deprecated"},
				{ID: "ADR-002", Title: "Superseded approach", Status: "superseded"},
			},
		},
	}
	cmds := BuildCommands{Build: "go build ./...", Test: "go test ./...", Lint: "golangci-lint run"}

	result, err := GenerateClaudeMD(dir, ds, cmds)
	require.NoError(t, err)

	assert.Contains(t, result, "ADR-001")
	assert.Contains(t, result, "deprecated")
	assert.Contains(t, result, "ADR-002")
	assert.Contains(t, result, "superseded")
}

// --- Merge tests ---

func TestMergeClaudeMD_FreshMerge(t *testing.T) {
	dir := t.TempDir()
	existing := `# my-project

This is my custom intro.

## Custom Section

My custom content here.
`
	ds := DataSourceInfo{
		Scout: &ScoutData{PrimaryLanguage: "Go", BuildSystem: "go"},
	}
	cmds := BuildCommands{Build: "go build ./...", Test: "go test ./...", Lint: "golangci-lint run"}

	result, err := MergeClaudeMD(existing, dir, ds, cmds)
	require.NoError(t, err)

	// User content must be preserved.
	assert.Contains(t, result, "This is my custom intro.")
	assert.Contains(t, result, "## Custom Section")
	assert.Contains(t, result, "My custom content here.")

	// Generated sections should be present.
	assert.Contains(t, result, "<!-- generated by sdp bootstrap:")
	assert.Contains(t, result, "<!-- end generated by sdp bootstrap -->")
}

func TestMergeClaudeMD_ExistingGeneratedSections(t *testing.T) {
	dir := t.TempDir()
	existing := `# my-project

My intro.

<!-- generated by sdp bootstrap: Tech Stack -->
## Tech Stack

- **Language:** Old (v1.0)
<!-- end generated by sdp bootstrap -->

## Custom Section

My custom content.
`
	ds := DataSourceInfo{
		Scout: &ScoutData{PrimaryLanguage: "Go", BuildSystem: "go"},
	}
	cmds := BuildCommands{Build: "go build ./...", Test: "go test ./...", Lint: "golangci-lint run"}

	result, err := MergeClaudeMD(existing, dir, ds, cmds)
	require.NoError(t, err)

	// User content preserved.
	assert.Contains(t, result, "My intro.")
	assert.Contains(t, result, "## Custom Section")
	assert.Contains(t, result, "My custom content.")

	// Generated section should be updated.
	assert.Contains(t, result, "Go")
	assert.Contains(t, result, "<!-- generated by sdp bootstrap: Tech Stack -->")
}

func TestMergeClaudeMD_UserContentNeverDeleted(t *testing.T) {
	dir := t.TempDir()
	existing := `# my-project

> My very important hand-written note that must survive.

## My Custom Workflow

1. Step one
2. Step two
3. Step three

### Sub-section

More details here.
`
	ds := DataSourceInfo{
		Scout: &ScoutData{PrimaryLanguage: "Go", BuildSystem: "go"},
	}
	cmds := BuildCommands{Build: "go build ./...", Test: "go test ./...", Lint: "golangci-lint run"}

	result, err := MergeClaudeMD(existing, dir, ds, cmds)
	require.NoError(t, err)

	assert.Contains(t, result, "My very important hand-written note that must survive.")
	assert.Contains(t, result, "## My Custom Workflow")
	assert.Contains(t, result, "Step one")
	assert.Contains(t, result, "Step two")
	assert.Contains(t, result, "Step three")
	assert.Contains(t, result, "### Sub-section")
	assert.Contains(t, result, "More details here.")
}

// --- Integration tests via Planner ---

func TestPlanner_Execute_GeneratesClaudeMD(t *testing.T) {
	dir := setupRepoWithScout(t)

	planner := NewPlanner(BootstrapConfig{RepoPath: dir, NoVerify: true})
	report, err := planner.Execute()
	require.NoError(t, err)

	// Verify CLAUDE.md was created.
	claudePath := filepath.Join(dir, "CLAUDE.md")
	assert.FileExists(t, claudePath)

	content, err := os.ReadFile(claudePath)
	require.NoError(t, err)

	// Should have generated markers (named markers).
	assert.Contains(t, string(content), "<!-- generated by sdp bootstrap: Tech Stack -->")
	assert.Contains(t, string(content), "## Tech Stack")
	assert.Contains(t, string(content), "## Architecture")

	// Find the claude_md artifact in report.
	var found bool
	for _, a := range report.Artifacts {
		if a.Type == "claude_md" {
			found = true
			assert.Equal(t, "ok", a.Status)
		}
	}
	assert.True(t, found)
}

func TestPlanner_Execute_ForceMerge_ClaudeMD(t *testing.T) {
	dir := setupRepoWithScout(t)
	existing := "# my-project\n\nMy custom intro.\n"
	require.NoError(t, os.WriteFile(filepath.Join(dir, "CLAUDE.md"), []byte(existing), 0o644))

	planner := NewPlanner(BootstrapConfig{RepoPath: dir, Force: true, NoVerify: true})
	report, err := planner.Execute()
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(dir, "CLAUDE.md"))
	require.NoError(t, err)

	// User content must survive.
	assert.Contains(t, string(content), "My custom intro.")

	// Generated content should be added.
	assert.Contains(t, string(content), "<!-- generated by sdp bootstrap:")

	// Report should show merge action for claude_md.
	var found bool
	for _, a := range report.Artifacts {
		if a.Type == "claude_md" && a.Action == "merge" {
			found = true
			assert.Equal(t, "ok", a.Status)
		}
	}
	assert.True(t, found)
}

// --- Helper tests ---

func TestDescribeComponent(t *testing.T) {
	tests := []struct {
		input    string
		contains string
	}{
		{"cmd/server", "CLI entrypoints"},
		{"internal/api", "API definitions"},
		{"pkg/utils", "Public packages"},
		{"scripts", "Build and utility scripts"},
		{"unknown", "unknown module"},
	}

	for _, tc := range tests {
		result := describeComponent(tc.input)
		assert.Contains(t, result, tc.contains, "for input: "+tc.input)
	}
}

func TestDefaultAntipatterns(t *testing.T) {
	ap := defaultAntipatterns()
	assert.NotEmpty(t, ap)
	assert.Contains(t, ap[0], "feature branches")
}

func TestBuildModuleList(t *testing.T) {
	ds := DataSourceInfo{
		Architect: &ArchitectData{
			Components: []string{"cmd/server", "internal/api", "internal/store"},
		},
	}
	modules := buildModuleList(ds)
	assert.Len(t, modules, 3)
	assert.Equal(t, "cmd/server", modules[0].Path)
}

func TestBuildModuleList_NoArchitect(t *testing.T) {
	ds := DataSourceInfo{}
	modules := buildModuleList(ds)
	assert.Nil(t, modules)
}

func TestBuildArchSummary(t *testing.T) {
	arch := &ArchitectData{
		Patterns:   []string{"hexagonal", "clean-architecture"},
		Components: []string{"cmd/server", "internal/api"},
		Decisions:  []ArchDecision{{ID: "ADR-001", Title: "Use Go", Status: "accepted"}},
	}
	summary := buildArchSummary(arch)
	assert.Contains(t, summary, "hexagonal")
	assert.Contains(t, summary, "clean-architecture")
	assert.Contains(t, summary, "1 architecture decision")
}

func TestDetectTestPattern(t *testing.T) {
	tests := []struct {
		lang string
		want string
	}{
		{"Go", "Go standard testing"},
		{"javascript", "Jest/Vitest"},
		{"python", "pytest"},
		{"rust", "Rust built-in tests"},
		{"unknown", "Standard test files"},
	}
	for _, tc := range tests {
		result := detectTestPattern(&ScoutData{PrimaryLanguage: tc.lang})
		assert.Contains(t, result, tc.want, "for language: "+tc.lang)
	}
}

func TestDetectRunCommand(t *testing.T) {
	assert.Equal(t, "go run ./...", detectRunCommand("go", BuildCommands{}))
	assert.Equal(t, "npm start", detectRunCommand("javascript", BuildCommands{}))
	assert.Equal(t, "cargo run", detectRunCommand("rust", BuildCommands{}))
	assert.Equal(t, "python -m <module>", detectRunCommand("python", BuildCommands{}))
}
