// Package adapters generates per-harness adapter files from an SDP manifest.
// Output is a map of relative path → file contents; the caller decides where
// to write them (typically .sdp/generated/).
package adapters

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"github.com/fall-out-bug/sdp_lab/internal/manifest"
)

var (
	tmplClaudeCommand = mustParse("claude-command", "templates/claude-code/command.tmpl")
	tmplClaudeAgent   = mustParse("claude-agent", "templates/claude-code/agent.tmpl")
	tmplOpenCodeAgent = mustParse("opencode-agent", "templates/opencode/agent.tmpl")
	tmplOpenCodeSkill = mustParse("opencode-skill", "templates/opencode/skill.tmpl")
	tmplCodexSkill    = mustParse("codex-skill", "templates/codex/skill.tmpl")
	tmplCursorCommand = mustParse("cursor-command", "templates/cursor/command.tmpl")
	tmplPiSkill       = mustParse("pi-skill", "templates/pi/skill.tmpl")
	tmplPiPrompt      = mustParse("pi-prompt", "templates/pi/prompt.tmpl")

	legacyClaudeSkillRef = regexp.MustCompile(`@?\.claude/skills/([A-Za-z0-9_-]+)/SKILL\.md`)
)

// renderItem is the template data type passed to all templates.
// Body holds the file contents referenced by Path/SystemPromptPath, or ""
// when path is empty or the file cannot be read (non-fatal).
type renderItem struct {
	Name    string
	Summary string
	Role    string // agents only
	Type    string // commands only
	Path    string // source path (relative to repo root)
	Body    string // contents of the file at Path, "" if unavailable
}

// readBody reads the file at filepath.Join(repoRoot, path) and returns its
// contents as a string.  If repoRoot is empty, path is empty, or the file
// cannot be read, it returns "" without error.
func readBody(repoRoot, path string) string {
	if repoRoot == "" || path == "" {
		return ""
	}
	data, err := os.ReadFile(filepath.Join(repoRoot, path))
	if err != nil {
		return ""
	}
	return string(data)
}

// wrapBodyWithMarker injects a "GENERATED by..." HTML comment block into body.
// If body begins with a YAML frontmatter (`---\n...\n---\n`), the marker is
// placed AFTER the closing `---` so harness frontmatter parsers (Claude Code,
// Cursor MDC) still see the YAML at line 1.  Otherwise the marker is placed
// at the top.  An empty body returns only the marker.
func wrapBodyWithMarker(body, sourcePath string) string {
	marker := fmt.Sprintf(
		"<!-- GENERATED by sdp generate-adapters from sdp.manifest.yaml — do not edit manually -->\n<!-- Source: %s -->\n",
		sourcePath,
	)
	if body == "" {
		return marker
	}
	if strings.HasPrefix(body, "---\n") {
		rest := body[len("---\n"):]
		if closeIdx := strings.Index(rest, "\n---\n"); closeIdx != -1 {
			insertAt := len("---\n") + closeIdx + len("\n---\n")
			return body[:insertAt] + marker + body[insertAt:]
		}
	}
	// No frontmatter — append marker as a trailing comment so the harness
	// parser still sees the original first line (description heuristics rely
	// on the first non-empty line).
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	return body + "\n" + marker
}

// stripFrontmatter removes a leading YAML frontmatter block (`---\n...\n---\n`)
// from body, returning the rest.  If body has no frontmatter, returns body
// unchanged.  Used by Cursor MDC rendering since the MDC template provides its
// own frontmatter — we don't want a second `---` block in the output.
func stripFrontmatter(body string) string {
	if !strings.HasPrefix(body, "---\n") {
		return body
	}
	rest := body[len("---\n"):]
	closeIdx := strings.Index(rest, "\n---\n")
	if closeIdx == -1 {
		return body
	}
	return rest[closeIdx+len("\n---\n"):]
}

// rewriteLegacyClaudeSkillRefsForPi converts Claude Code skill-path hints in
// shared command bodies to Pi-native skill names. The shared prompt sources stay
// harness-neutral-ish, while Pi prompt templates avoid leaking .claude paths.
func rewriteLegacyClaudeSkillRefsForPi(body string) string {
	return legacyClaudeSkillRef.ReplaceAllString(body, `$1`)
}

// Generate renders adapter files for all harnesses declared in the manifest.
// repoRoot is used to resolve relative paths declared in the manifest so that
// file bodies can be embedded in the generated output.  Pass "" to skip body
// embedding (useful in tests that don't have filesystem fixtures).
// Returns a deterministic map of relative output path → file contents.
// Relative paths are anchored at the repo root (e.g. ".sdp/generated/.claude/commands/build.md").
func Generate(m *manifest.Manifest, repoRoot string) (map[string][]byte, error) {
	out := make(map[string][]byte)

	allHarnesses := m.Harnesses
	if len(allHarnesses) == 0 {
		allHarnesses = []manifest.Harness{
			manifest.HarnessClaudeCode,
			manifest.HarnessOpenCode,
			manifest.HarnessCodex,
			manifest.HarnessCursor,
			manifest.HarnessPi,
		}
	}
	harnessEnabled := make(map[manifest.Harness]bool, len(allHarnesses))
	for _, h := range allHarnesses {
		harnessEnabled[h] = true
	}

	if err := generateClaudeCode(m, harnessEnabled, repoRoot, out); err != nil {
		return nil, err
	}
	if err := generateOpenCode(m, harnessEnabled, repoRoot, out); err != nil {
		return nil, err
	}
	if err := generateCodex(m, harnessEnabled, repoRoot, out); err != nil {
		return nil, err
	}
	if err := generateCursor(m, harnessEnabled, repoRoot, out); err != nil {
		return nil, err
	}
	if err := generatePi(m, harnessEnabled, repoRoot, out); err != nil {
		return nil, err
	}
	if err := validateOutputPaths(out); err != nil {
		return nil, err
	}

	return out, nil
}

func validateOutputPaths(out map[string][]byte) error {
	for rel := range out {
		if err := validateOutputPath(rel); err != nil {
			return err
		}
	}
	return nil
}

func validateOutputPath(rel string) error {
	if rel == "" {
		return fmt.Errorf("adapter output path is empty")
	}
	if filepath.IsAbs(rel) {
		return fmt.Errorf("adapter output path %q must be relative", rel)
	}
	slashPath := strings.ReplaceAll(rel, "\\", "/")
	for _, part := range strings.Split(slashPath, "/") {
		if part == ".." {
			return fmt.Errorf("adapter output path %q must not contain parent traversal", rel)
		}
	}
	return nil
}

// itemHarnesses returns the effective harness set for an item: if the item's
// own Harnesses list is empty, it inherits all harnesses enabled in the manifest.
func itemHarnesses(declared []manifest.Harness, manifestEnabled map[manifest.Harness]bool) map[manifest.Harness]bool {
	if len(declared) == 0 {
		// empty list = "all manifest harnesses"
		return manifestEnabled
	}
	out := make(map[manifest.Harness]bool, len(declared))
	for _, h := range declared {
		if manifestEnabled[h] {
			out[h] = true
		}
	}
	return out
}

func commandOutputPath(c manifest.Command, h manifest.Harness, fallback string) string {
	if c.Dispatch != nil {
		if path := strings.TrimSpace(c.Dispatch[h]); path != "" {
			return path
		}
	}
	return fallback
}

func render(t *template.Template, data any) ([]byte, error) {
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// generateClaudeCode emits .claude/commands/<name>.md and .claude/agents/<name>.md
func generateClaudeCode(m *manifest.Manifest, enabled map[manifest.Harness]bool, repoRoot string, out map[string][]byte) error {
	if !enabled[manifest.HarnessClaudeCode] {
		return nil
	}

	// Sort commands for determinism
	cmds := make([]manifest.Command, len(m.Commands))
	copy(cmds, m.Commands)
	sort.Slice(cmds, func(i, j int) bool { return cmds[i].Name < cmds[j].Name })

	for _, c := range cmds {
		ih := itemHarnesses(c.Harnesses, enabled)
		if !ih[manifest.HarnessClaudeCode] {
			continue
		}
		item := renderItem{
			Name:    c.Name,
			Summary: c.Summary,
			Type:    c.Type,
			Path:    c.Path,
			Body:    wrapBodyWithMarker(readBody(repoRoot, c.Path), c.Path),
		}
		data, err := render(tmplClaudeCommand, item)
		if err != nil {
			return err
		}
		out[commandOutputPath(c, manifest.HarnessClaudeCode, ".claude/commands/"+c.Name+".md")] = data
	}

	// Sort agents for determinism
	agents := make([]manifest.Agent, len(m.Agents))
	copy(agents, m.Agents)
	sort.Slice(agents, func(i, j int) bool { return agents[i].Name < agents[j].Name })

	for _, a := range agents {
		ih := itemHarnesses(a.Harnesses, enabled)
		if !ih[manifest.HarnessClaudeCode] {
			continue
		}
		item := renderItem{
			Name:    a.Name,
			Summary: a.Summary,
			Role:    a.Role,
			Path:    a.SystemPromptPath,
			Body:    wrapBodyWithMarker(readBody(repoRoot, a.SystemPromptPath), a.SystemPromptPath),
		}
		data, err := render(tmplClaudeAgent, item)
		if err != nil {
			return err
		}
		out[".claude/agents/"+a.Name+".md"] = data
	}
	return nil
}

// generateOpenCode emits .opencode/agent/<name>.json and .opencode/skill/<name>.md
func generateOpenCode(m *manifest.Manifest, enabled map[manifest.Harness]bool, repoRoot string, out map[string][]byte) error {
	if !enabled[manifest.HarnessOpenCode] {
		return nil
	}

	agents := make([]manifest.Agent, len(m.Agents))
	copy(agents, m.Agents)
	sort.Slice(agents, func(i, j int) bool { return agents[i].Name < agents[j].Name })

	for _, a := range agents {
		ih := itemHarnesses(a.Harnesses, enabled)
		if !ih[manifest.HarnessOpenCode] {
			continue
		}
		item := renderItem{
			Name:    a.Name,
			Summary: a.Summary,
			Role:    a.Role,
			Path:    a.SystemPromptPath,
			// Body intentionally omitted for OpenCode JSON: body goes in separate .md per design
		}
		data, err := render(tmplOpenCodeAgent, item)
		if err != nil {
			return err
		}
		out[".opencode/agent/"+a.Name+".json"] = data
	}

	skills := make([]manifest.Skill, len(m.Skills))
	copy(skills, m.Skills)
	sort.Slice(skills, func(i, j int) bool { return skills[i].Name < skills[j].Name })

	for _, s := range skills {
		ih := itemHarnesses(s.Harnesses, enabled)
		if !ih[manifest.HarnessOpenCode] {
			continue
		}
		item := renderItem{
			Name:    s.Name,
			Summary: s.Summary,
			Path:    s.Path,
			Body:    wrapBodyWithMarker(readBody(repoRoot, s.Path), s.Path),
		}
		data, err := render(tmplOpenCodeSkill, item)
		if err != nil {
			return err
		}
		out[".opencode/skill/"+s.Name+".md"] = data
	}
	return nil
}

// generateCodex emits .codex/skills/<name>.md
func generateCodex(m *manifest.Manifest, enabled map[manifest.Harness]bool, repoRoot string, out map[string][]byte) error {
	if !enabled[manifest.HarnessCodex] {
		return nil
	}

	skills := make([]manifest.Skill, len(m.Skills))
	copy(skills, m.Skills)
	sort.Slice(skills, func(i, j int) bool { return skills[i].Name < skills[j].Name })

	for _, s := range skills {
		ih := itemHarnesses(s.Harnesses, enabled)
		if !ih[manifest.HarnessCodex] {
			continue
		}
		item := renderItem{
			Name:    s.Name,
			Summary: s.Summary,
			Path:    s.Path,
			Body:    wrapBodyWithMarker(readBody(repoRoot, s.Path), s.Path),
		}
		data, err := render(tmplCodexSkill, item)
		if err != nil {
			return err
		}
		out[".codex/skills/"+s.Name+".md"] = data
	}
	return nil
}

// generateCursor emits .cursor/rules/<name>.mdc
func generateCursor(m *manifest.Manifest, enabled map[manifest.Harness]bool, repoRoot string, out map[string][]byte) error {
	if !enabled[manifest.HarnessCursor] {
		return nil
	}

	cmds := make([]manifest.Command, len(m.Commands))
	copy(cmds, m.Commands)
	sort.Slice(cmds, func(i, j int) bool { return cmds[i].Name < cmds[j].Name })

	for _, c := range cmds {
		ih := itemHarnesses(c.Harnesses, enabled)
		if !ih[manifest.HarnessCursor] {
			continue
		}
		item := renderItem{
			Name:    c.Name,
			Summary: c.Summary,
			Type:    c.Type,
			Path:    c.Path,
			Body:    stripFrontmatter(readBody(repoRoot, c.Path)),
		}
		data, err := render(tmplCursorCommand, item)
		if err != nil {
			return err
		}
		out[commandOutputPath(c, manifest.HarnessCursor, ".cursor/rules/"+c.Name+".mdc")] = data
	}
	return nil
}

// generatePi emits skills, agent prompts, and command prompts in Pi's native
// project layout. Pi auto-loads .pi/skills/<name>/SKILL.md as callable skills
// and .pi/prompts/<name>.md as slash prompt templates.
func generatePi(m *manifest.Manifest, enabled map[manifest.Harness]bool, repoRoot string, out map[string][]byte) error {
	if !enabled[manifest.HarnessPi] {
		return nil
	}

	skills := make([]manifest.Skill, len(m.Skills))
	copy(skills, m.Skills)
	sort.Slice(skills, func(i, j int) bool { return skills[i].Name < skills[j].Name })

	for _, s := range skills {
		ih := itemHarnesses(s.Harnesses, enabled)
		if !ih[manifest.HarnessPi] {
			continue
		}
		item := renderItem{
			Name:    s.Name,
			Summary: s.Summary,
			Path:    s.Path,
			Body:    wrapBodyWithMarker(readBody(repoRoot, s.Path), s.Path),
		}
		data, err := render(tmplPiSkill, item)
		if err != nil {
			return err
		}
		out[".pi/skills/"+s.Name+"/SKILL.md"] = data
	}

	agents := make([]manifest.Agent, len(m.Agents))
	copy(agents, m.Agents)
	sort.Slice(agents, func(i, j int) bool { return agents[i].Name < agents[j].Name })

	for _, a := range agents {
		ih := itemHarnesses(a.Harnesses, enabled)
		if !ih[manifest.HarnessPi] {
			continue
		}
		item := renderItem{
			Name:    a.Name,
			Summary: a.Summary,
			Role:    a.Role,
			Path:    a.SystemPromptPath,
			Body:    wrapBodyWithMarker(readBody(repoRoot, a.SystemPromptPath), a.SystemPromptPath),
		}
		data, err := render(tmplPiSkill, item)
		if err != nil {
			return err
		}
		out[".pi/skills/"+a.Name+"/SKILL.md"] = data
	}

	cmds := make([]manifest.Command, len(m.Commands))
	copy(cmds, m.Commands)
	sort.Slice(cmds, func(i, j int) bool { return cmds[i].Name < cmds[j].Name })

	for _, c := range cmds {
		ih := itemHarnesses(c.Harnesses, enabled)
		if !ih[manifest.HarnessPi] {
			continue
		}
		item := renderItem{
			Name:    c.Name,
			Summary: c.Summary,
			Type:    c.Type,
			Path:    c.Path,
			Body:    rewriteLegacyClaudeSkillRefsForPi(stripFrontmatter(readBody(repoRoot, c.Path))),
		}
		data, err := render(tmplPiPrompt, item)
		if err != nil {
			return err
		}
		out[commandOutputPath(c, manifest.HarnessPi, ".pi/prompts/"+c.Name+".md")] = data
	}

	return nil
}
