apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sdp-control
resources:
  - brain-gateway.yaml
  - scheduler.yaml
  - policy-service.yaml
  - nats.yaml
  - intake-gateway.yaml
  - swarm-orchestrator.yaml
