apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swarm-workspaces
  namespace: sdp-control
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: optional - use cluster default
