package profile

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type AdapterEndpoint struct {
	System       string
	Endpoint     string
	ContractPath string
	Version      string
	Enabled      bool
}

type GuardScope struct {
	Name         string
	Path         string
	Description  string
	EvidencePath string
	Enabled      bool
}

type ProfileConfig struct {
	ProfileName    string
	Version        string
	Adapters       []AdapterEndpoint
	GuardScopes    []GuardScope
	EvidencePath   string
	CheckpointsDir string
	FindingsDir    string
	SessionsDir    string
	TracesDir      string
}

func NewOSSCombineConfig() *ProfileConfig {
	return &ProfileConfig{
		ProfileName:    "oss-combine",
		Version:        "1.0.0",
		EvidencePath:   ".sdp/evidence",
		CheckpointsDir: ".sdp/checkpoints",
		FindingsDir:    ".sdp/findings",
		SessionsDir:    ".sdp/sessions",
		TracesDir:      ".sdp/traces",
		Adapters: []AdapterEndpoint{
			{
				System:       "omo",
				Endpoint:     "opencode://session",
				ContractPath: "schema/contracts/orchestration-event.schema.json",
				Version:      "1.0.0",
				Enabled:      true,
			},
			{
				System:       "beads",
				Endpoint:     "beads://local",
				ContractPath: "schema/contracts/runtime-decision.schema.json",
				Version:      "1.0.0",
				Enabled:      true,
			},
			{
				System:       "gas-town",
				Endpoint:     "gastown://build",
				ContractPath: "schema/contracts/orchestration-event.schema.json",
				Version:      "1.0.0",
				Enabled:      true,
			},
			{
				System:       "sdp-lab",
				Endpoint:     "sdp://internal",
				ContractPath: "schema/contracts/runtime-decision.schema.json",
				Version:      "1.0.0",
				Enabled:      true,
			},
		},
		GuardScopes: []GuardScope{
			{
				Name:         "default",
				Path:         "docs/workstreams/backlog",
				Description:  "Default workstream scope for task execution",
				EvidencePath: ".sdp/evidence",
				Enabled:      true,
			},
			{
				Name:         "contracts",
				Path:         "internal/adapters",
				Description:  "Adapter contract scope for SDK development",
				EvidencePath: ".sdp/evidence",
				Enabled:      true,
			},
			{
				Name:         "bridge",
				Path:         "internal/bridge",
				Description:  "GitHub-Beads bridge scope for findings sync",
				EvidencePath: ".sdp/evidence",
				Enabled:      true,
			},
		},
	}
}

func (c *ProfileConfig) ToYAML() (string, error) {
	tmpl := `# SDP Profile Configuration
# Generated by: sdp up --profile {{.ProfileName}}
# Version: {{.Version}}

profile:
  name: {{.ProfileName}}
  version: {{.Version}}

adapters:
{{- range .Adapters}}
  - system: {{.System}}
    endpoint: {{.Endpoint}}
    contract: {{.ContractPath}}
    version: {{.Version}}
    enabled: {{.Enabled}}
{{- end}}

guard:
  scopes:
{{- range .GuardScopes}}
    - name: {{.Name}}
      path: {{.Path}}
      description: {{.Description}}
      evidence_path: {{.EvidencePath}}
      enabled: {{.Enabled}}
{{- end}}

paths:
  evidence: {{.EvidencePath}}
  checkpoints: {{.CheckpointsDir}}
  findings: {{.FindingsDir}}
  sessions: {{.SessionsDir}}
  traces: {{.TracesDir}}
`
	t, err := template.New("config").Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf strings.Builder
	if err := t.Execute(&buf, c); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	return buf.String(), nil
}

func (c *ProfileConfig) ToAdaptersYAML() (string, error) {
	tmpl := `# Adapter Endpoints Configuration
# Profile: {{.ProfileName}} v{{.Version}}

adapters:
{{- range .Adapters}}
  {{.System}}:
    endpoint: {{.Endpoint}}
    contract: {{.ContractPath}}
    version: {{.Version}}
    enabled: {{.Enabled}}
{{- end}}
`
	t, err := template.New("adapters").Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf strings.Builder
	if err := t.Execute(&buf, c); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	return buf.String(), nil
}

func (c *ProfileConfig) ToGuardYAML() (string, error) {
	tmpl := `# Guard Scope Configuration
# Profile: {{.ProfileName}} v{{.Version}}

guard:
  default_scope: default
  evidence_path: {{.EvidencePath}}
  
  scopes:
{{- range .GuardScopes}}
    {{.Name}}:
      path: {{.Path}}
      description: {{.Description}}
      evidence_path: {{.EvidencePath}}
      enabled: {{.Enabled}}
{{- end}}
`
	t, err := template.New("guard").Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf strings.Builder
	if err := t.Execute(&buf, c); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	return buf.String(), nil
}

func (c *ProfileConfig) GenerateConfigs(outputDir string, dryRun bool) error {
	configs := []struct {
		name    string
		content func() (string, error)
	}{
		{"config.yaml", c.ToYAML},
		{"adapters.yaml", c.ToAdaptersYAML},
		{"guard.yaml", c.ToGuardYAML},
	}

	for _, cfg := range configs {
		content, err := cfg.content()
		if err != nil {
			return fmt.Errorf("generate %s: %w", cfg.name, err)
		}

		path := filepath.Join(outputDir, cfg.name)
		if dryRun {
			fmt.Printf("  [DRY-RUN] Would create: %s (%d bytes)\n", path, len(content))
			continue
		}

		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return fmt.Errorf("create parent dir for %s: %w", path, err)
		}

		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}

		fmt.Printf("  ✓ %s\n", cfg.name)
	}

	return nil
}

type ConfigValidator struct {
	config *ProfileConfig
}

func NewConfigValidator(config *ProfileConfig) *ConfigValidator {
	return &ConfigValidator{config: config}
}

func (v *ConfigValidator) Validate() []ConfigValidationError {
	var errors []ConfigValidationError

	for _, adapter := range v.config.Adapters {
		if adapter.Enabled {
			if adapter.Endpoint == "" {
				errors = append(errors, ConfigValidationError{
					Field:   fmt.Sprintf("adapters.%s.endpoint", adapter.System),
					Message: "endpoint is required for enabled adapter",
				})
			}
			if adapter.ContractPath == "" {
				errors = append(errors, ConfigValidationError{
					Field:   fmt.Sprintf("adapters.%s.contract", adapter.System),
					Message: "contract path is required for enabled adapter",
				})
			}
			if adapter.Version == "" {
				errors = append(errors, ConfigValidationError{
					Field:   fmt.Sprintf("adapters.%s.version", adapter.System),
					Message: "version is required for enabled adapter",
				})
			}
		}
	}

	for _, scope := range v.config.GuardScopes {
		if scope.Enabled {
			if scope.Path == "" {
				errors = append(errors, ConfigValidationError{
					Field:   fmt.Sprintf("guard.scopes.%s.path", scope.Name),
					Message: "path is required for enabled scope",
				})
			}
			if scope.EvidencePath == "" {
				errors = append(errors, ConfigValidationError{
					Field:   fmt.Sprintf("guard.scopes.%s.evidence_path", scope.Name),
					Message: "evidence path is required for enabled scope",
				})
			}
		}
	}

	if v.config.EvidencePath == "" {
		errors = append(errors, ConfigValidationError{
			Field:   "paths.evidence",
			Message: "evidence path is required",
		})
	}

	return errors
}

type ConfigValidationError struct {
	Field   string
	Message string
}

func (e ConfigValidationError) Error() string {
	return fmt.Sprintf("%s: %s", e.Field, e.Message)
}

func ValidateConfigLint(configPath string) error {
	content, err := os.ReadFile(configPath)
	if err != nil {
		return fmt.Errorf("read config: %w", err)
	}

	requiredFields := []string{
		"profile:",
		"adapters:",
		"guard:",
		"paths:",
	}

	var missing []string
	for _, field := range requiredFields {
		if !strings.Contains(string(content), field) {
			missing = append(missing, field)
		}
	}

	if len(missing) > 0 {
		return fmt.Errorf("missing required fields: %s", strings.Join(missing, ", "))
	}

	return nil
}
