apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - workspace-pvc.yaml
patches:
  - target:
      kind: Deployment
      name: adapter-controller
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/volumes/0
        value:
          name: workspaces
          persistentVolumeClaim:
            claimName: adapter-workspaces
labels:
  - pairs:
      sdp.dev/environment: prod
