// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package pb

// This is a mock generated file for testing purposes.

type HelloRequest struct {
	Name string
}

type HelloReply struct {
	Message string
}
